// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v3.19.1
// source: action_query.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ActionStep, ActionSubProgram, ActionVariable, RequestContext, ValidationIssue } from "./common";

export interface GetActionRequest {
  actionId: string;
  context?: RequestContext | undefined;
}

/**
 * Web program editor envelope (camelCase JSON for actionId, steps, …).
 * Not a second persistence model: native XAction JSON in ActionCatalogItem.data is parsed as XActionData
 * (x_action_program.proto, PascalCase json_name) and mapped here for the SPA.
 */
export interface GetActionResponse {
  actionId: string;
  version: number;
  steps: ActionStep[];
  variables: ActionVariable[];
  subPrograms: ActionSubProgram[];
}

export interface GetStepSchemasRequest {
  context?: RequestContext | undefined;
}

export interface GetStepRunnersRequest {
  context?: RequestContext | undefined;
}

export interface StepRunnerSubItem {
  key: string;
  name: string;
  description: string;
}

/** One enum/list option (Quicker.Domain.Actions.X.StepRunners.SelectionItem). */
export interface StepRunnerParamSelectionItem {
  value: string;
  name: string;
  description: string;
}

/**
 * Input parameter definition for web editors (Quicker.Domain.Actions.X.StepRunners.StepInParamDef).
 * var_type / internal_type / variable_mode are C# enum underlying int values.
 */
export interface StepRunnerInputParamDef {
  key: string;
  name: string;
  description: string;
  varType: number;
  internalType?: number | undefined;
  variableMode: number;
  isMultiLine: boolean;
  isRequired: boolean;
  validationPattern: string;
  selectionItems: StepRunnerParamSelectionItem[];
  isControlField: boolean;
  defaultValue: string;
  fromOldField: string;
  isAdvanced: boolean;
  allowInput: boolean;
  visibleExpression: string;
  replaceVariable: boolean;
  defaultHighlightType: string;
  skipEval: boolean;
  skipLogContent: boolean;
  validForList: string[];
  invalidForList: string[];
}

/** Output parameter definition for web editors (Quicker.Domain.Actions.X.StepRunners.StepOutParamDef). */
export interface StepRunnerOutputParamDef {
  key: string;
  name: string;
  description: string;
  varType: number;
  isAdvanced: boolean;
  visibleExpression: string;
  customTypeName: string;
  skipLogContent: boolean;
  validForList: string[];
  invalidForList: string[];
}

export interface StepRunnerItem {
  key: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  secondaryCategories: string[];
  keywords: string[];
  supportedParams: string[];
  subItems: StepRunnerSubItem[];
  /** Quicker.Domain.Actions.X.Storage.StepType as string (e.g. If, Loop, Action). */
  stepType: string;
  inputParamDefs: StepRunnerInputParamDef[];
  outputParamDefs: StepRunnerOutputParamDef[];
}

export interface GetStepRunnersResponse {
  count: number;
  items: StepRunnerItem[];
}

export interface StepSchema {
  stepType: string;
  title: string;
  supportedParams: string[];
}

export interface GetStepSchemasResponse {
  schemas: StepSchema[];
}

export interface ValidateActionRequest {
  actionId: string;
  context?: RequestContext | undefined;
}

export interface ValidateActionResponse {
  issues: ValidationIssue[];
}

function createBaseGetActionRequest(): GetActionRequest {
  return { actionId: "", context: undefined };
}

export const GetActionRequest: MessageFns<GetActionRequest> = {
  encode(message: GetActionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.actionId !== "") {
      writer.uint32(10).string(message.actionId);
    }
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetActionRequest {
    return {
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
    };
  },

  toJSON(message: GetActionRequest): unknown {
    const obj: any = {};
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetActionRequest>, I>>(base?: I): GetActionRequest {
    return GetActionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetActionRequest>, I>>(object: I): GetActionRequest {
    const message = createBaseGetActionRequest();
    message.actionId = object.actionId ?? "";
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    return message;
  },
};

function createBaseGetActionResponse(): GetActionResponse {
  return { actionId: "", version: 0, steps: [], variables: [], subPrograms: [] };
}

export const GetActionResponse: MessageFns<GetActionResponse> = {
  encode(message: GetActionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.actionId !== "") {
      writer.uint32(10).string(message.actionId);
    }
    if (message.version !== 0) {
      writer.uint32(16).int64(message.version);
    }
    for (const v of message.steps) {
      ActionStep.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.variables) {
      ActionVariable.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.subPrograms) {
      ActionSubProgram.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.version = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.steps.push(ActionStep.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.variables.push(ActionVariable.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.subPrograms.push(ActionSubProgram.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetActionResponse {
    return {
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
      steps: globalThis.Array.isArray(object?.steps) ? object.steps.map((e: any) => ActionStep.fromJSON(e)) : [],
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => ActionVariable.fromJSON(e))
        : [],
      subPrograms: globalThis.Array.isArray(object?.subPrograms)
        ? object.subPrograms.map((e: any) => ActionSubProgram.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetActionResponse): unknown {
    const obj: any = {};
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    if (message.steps?.length) {
      obj.steps = message.steps.map((e) => ActionStep.toJSON(e));
    }
    if (message.variables?.length) {
      obj.variables = message.variables.map((e) => ActionVariable.toJSON(e));
    }
    if (message.subPrograms?.length) {
      obj.subPrograms = message.subPrograms.map((e) => ActionSubProgram.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetActionResponse>, I>>(base?: I): GetActionResponse {
    return GetActionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetActionResponse>, I>>(object: I): GetActionResponse {
    const message = createBaseGetActionResponse();
    message.actionId = object.actionId ?? "";
    message.version = object.version ?? 0;
    message.steps = object.steps?.map((e) => ActionStep.fromPartial(e)) || [];
    message.variables = object.variables?.map((e) => ActionVariable.fromPartial(e)) || [];
    message.subPrograms = object.subPrograms?.map((e) => ActionSubProgram.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetStepSchemasRequest(): GetStepSchemasRequest {
  return { context: undefined };
}

export const GetStepSchemasRequest: MessageFns<GetStepSchemasRequest> = {
  encode(message: GetStepSchemasRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStepSchemasRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStepSchemasRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStepSchemasRequest {
    return { context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined };
  },

  toJSON(message: GetStepSchemasRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStepSchemasRequest>, I>>(base?: I): GetStepSchemasRequest {
    return GetStepSchemasRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStepSchemasRequest>, I>>(object: I): GetStepSchemasRequest {
    const message = createBaseGetStepSchemasRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    return message;
  },
};

function createBaseGetStepRunnersRequest(): GetStepRunnersRequest {
  return { context: undefined };
}

export const GetStepRunnersRequest: MessageFns<GetStepRunnersRequest> = {
  encode(message: GetStepRunnersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStepRunnersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStepRunnersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStepRunnersRequest {
    return { context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined };
  },

  toJSON(message: GetStepRunnersRequest): unknown {
    const obj: any = {};
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStepRunnersRequest>, I>>(base?: I): GetStepRunnersRequest {
    return GetStepRunnersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStepRunnersRequest>, I>>(object: I): GetStepRunnersRequest {
    const message = createBaseGetStepRunnersRequest();
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    return message;
  },
};

function createBaseStepRunnerSubItem(): StepRunnerSubItem {
  return { key: "", name: "", description: "" };
}

export const StepRunnerSubItem: MessageFns<StepRunnerSubItem> = {
  encode(message: StepRunnerSubItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepRunnerSubItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepRunnerSubItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepRunnerSubItem {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: StepRunnerSubItem): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepRunnerSubItem>, I>>(base?: I): StepRunnerSubItem {
    return StepRunnerSubItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepRunnerSubItem>, I>>(object: I): StepRunnerSubItem {
    const message = createBaseStepRunnerSubItem();
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseStepRunnerParamSelectionItem(): StepRunnerParamSelectionItem {
  return { value: "", name: "", description: "" };
}

export const StepRunnerParamSelectionItem: MessageFns<StepRunnerParamSelectionItem> = {
  encode(message: StepRunnerParamSelectionItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.value !== "") {
      writer.uint32(10).string(message.value);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepRunnerParamSelectionItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepRunnerParamSelectionItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.value = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepRunnerParamSelectionItem {
    return {
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
    };
  },

  toJSON(message: StepRunnerParamSelectionItem): unknown {
    const obj: any = {};
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepRunnerParamSelectionItem>, I>>(base?: I): StepRunnerParamSelectionItem {
    return StepRunnerParamSelectionItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepRunnerParamSelectionItem>, I>>(object: I): StepRunnerParamSelectionItem {
    const message = createBaseStepRunnerParamSelectionItem();
    message.value = object.value ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    return message;
  },
};

function createBaseStepRunnerInputParamDef(): StepRunnerInputParamDef {
  return {
    key: "",
    name: "",
    description: "",
    varType: 0,
    internalType: undefined,
    variableMode: 0,
    isMultiLine: false,
    isRequired: false,
    validationPattern: "",
    selectionItems: [],
    isControlField: false,
    defaultValue: "",
    fromOldField: "",
    isAdvanced: false,
    allowInput: false,
    visibleExpression: "",
    replaceVariable: false,
    defaultHighlightType: "",
    skipEval: false,
    skipLogContent: false,
    validForList: [],
    invalidForList: [],
  };
}

export const StepRunnerInputParamDef: MessageFns<StepRunnerInputParamDef> = {
  encode(message: StepRunnerInputParamDef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.varType !== 0) {
      writer.uint32(32).int32(message.varType);
    }
    if (message.internalType !== undefined) {
      writer.uint32(40).int32(message.internalType);
    }
    if (message.variableMode !== 0) {
      writer.uint32(48).int32(message.variableMode);
    }
    if (message.isMultiLine !== false) {
      writer.uint32(56).bool(message.isMultiLine);
    }
    if (message.isRequired !== false) {
      writer.uint32(64).bool(message.isRequired);
    }
    if (message.validationPattern !== "") {
      writer.uint32(74).string(message.validationPattern);
    }
    for (const v of message.selectionItems) {
      StepRunnerParamSelectionItem.encode(v!, writer.uint32(82).fork()).join();
    }
    if (message.isControlField !== false) {
      writer.uint32(88).bool(message.isControlField);
    }
    if (message.defaultValue !== "") {
      writer.uint32(98).string(message.defaultValue);
    }
    if (message.fromOldField !== "") {
      writer.uint32(106).string(message.fromOldField);
    }
    if (message.isAdvanced !== false) {
      writer.uint32(112).bool(message.isAdvanced);
    }
    if (message.allowInput !== false) {
      writer.uint32(120).bool(message.allowInput);
    }
    if (message.visibleExpression !== "") {
      writer.uint32(130).string(message.visibleExpression);
    }
    if (message.replaceVariable !== false) {
      writer.uint32(136).bool(message.replaceVariable);
    }
    if (message.defaultHighlightType !== "") {
      writer.uint32(146).string(message.defaultHighlightType);
    }
    if (message.skipEval !== false) {
      writer.uint32(152).bool(message.skipEval);
    }
    if (message.skipLogContent !== false) {
      writer.uint32(160).bool(message.skipLogContent);
    }
    for (const v of message.validForList) {
      writer.uint32(170).string(v!);
    }
    for (const v of message.invalidForList) {
      writer.uint32(178).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepRunnerInputParamDef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepRunnerInputParamDef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.varType = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.internalType = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.variableMode = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isMultiLine = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isRequired = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.validationPattern = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.selectionItems.push(StepRunnerParamSelectionItem.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.isControlField = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.defaultValue = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.fromOldField = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.isAdvanced = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.allowInput = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.visibleExpression = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 136) {
            break;
          }

          message.replaceVariable = reader.bool();
          continue;
        }
        case 18: {
          if (tag !== 146) {
            break;
          }

          message.defaultHighlightType = reader.string();
          continue;
        }
        case 19: {
          if (tag !== 152) {
            break;
          }

          message.skipEval = reader.bool();
          continue;
        }
        case 20: {
          if (tag !== 160) {
            break;
          }

          message.skipLogContent = reader.bool();
          continue;
        }
        case 21: {
          if (tag !== 170) {
            break;
          }

          message.validForList.push(reader.string());
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.invalidForList.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepRunnerInputParamDef {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      varType: isSet(object.varType) ? globalThis.Number(object.varType) : 0,
      internalType: isSet(object.internalType) ? globalThis.Number(object.internalType) : undefined,
      variableMode: isSet(object.variableMode) ? globalThis.Number(object.variableMode) : 0,
      isMultiLine: isSet(object.isMultiLine) ? globalThis.Boolean(object.isMultiLine) : false,
      isRequired: isSet(object.isRequired) ? globalThis.Boolean(object.isRequired) : false,
      validationPattern: isSet(object.validationPattern) ? globalThis.String(object.validationPattern) : "",
      selectionItems: globalThis.Array.isArray(object?.selectionItems)
        ? object.selectionItems.map((e: any) => StepRunnerParamSelectionItem.fromJSON(e))
        : [],
      isControlField: isSet(object.isControlField) ? globalThis.Boolean(object.isControlField) : false,
      defaultValue: isSet(object.defaultValue) ? globalThis.String(object.defaultValue) : "",
      fromOldField: isSet(object.fromOldField) ? globalThis.String(object.fromOldField) : "",
      isAdvanced: isSet(object.isAdvanced) ? globalThis.Boolean(object.isAdvanced) : false,
      allowInput: isSet(object.allowInput) ? globalThis.Boolean(object.allowInput) : false,
      visibleExpression: isSet(object.visibleExpression) ? globalThis.String(object.visibleExpression) : "",
      replaceVariable: isSet(object.replaceVariable) ? globalThis.Boolean(object.replaceVariable) : false,
      defaultHighlightType: isSet(object.defaultHighlightType) ? globalThis.String(object.defaultHighlightType) : "",
      skipEval: isSet(object.skipEval) ? globalThis.Boolean(object.skipEval) : false,
      skipLogContent: isSet(object.skipLogContent) ? globalThis.Boolean(object.skipLogContent) : false,
      validForList: globalThis.Array.isArray(object?.validForList)
        ? object.validForList.map((e: any) => globalThis.String(e))
        : [],
      invalidForList: globalThis.Array.isArray(object?.invalidForList)
        ? object.invalidForList.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: StepRunnerInputParamDef): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.varType !== 0) {
      obj.varType = Math.round(message.varType);
    }
    if (message.internalType !== undefined) {
      obj.internalType = Math.round(message.internalType);
    }
    if (message.variableMode !== 0) {
      obj.variableMode = Math.round(message.variableMode);
    }
    if (message.isMultiLine !== false) {
      obj.isMultiLine = message.isMultiLine;
    }
    if (message.isRequired !== false) {
      obj.isRequired = message.isRequired;
    }
    if (message.validationPattern !== "") {
      obj.validationPattern = message.validationPattern;
    }
    if (message.selectionItems?.length) {
      obj.selectionItems = message.selectionItems.map((e) => StepRunnerParamSelectionItem.toJSON(e));
    }
    if (message.isControlField !== false) {
      obj.isControlField = message.isControlField;
    }
    if (message.defaultValue !== "") {
      obj.defaultValue = message.defaultValue;
    }
    if (message.fromOldField !== "") {
      obj.fromOldField = message.fromOldField;
    }
    if (message.isAdvanced !== false) {
      obj.isAdvanced = message.isAdvanced;
    }
    if (message.allowInput !== false) {
      obj.allowInput = message.allowInput;
    }
    if (message.visibleExpression !== "") {
      obj.visibleExpression = message.visibleExpression;
    }
    if (message.replaceVariable !== false) {
      obj.replaceVariable = message.replaceVariable;
    }
    if (message.defaultHighlightType !== "") {
      obj.defaultHighlightType = message.defaultHighlightType;
    }
    if (message.skipEval !== false) {
      obj.skipEval = message.skipEval;
    }
    if (message.skipLogContent !== false) {
      obj.skipLogContent = message.skipLogContent;
    }
    if (message.validForList?.length) {
      obj.validForList = message.validForList;
    }
    if (message.invalidForList?.length) {
      obj.invalidForList = message.invalidForList;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepRunnerInputParamDef>, I>>(base?: I): StepRunnerInputParamDef {
    return StepRunnerInputParamDef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepRunnerInputParamDef>, I>>(object: I): StepRunnerInputParamDef {
    const message = createBaseStepRunnerInputParamDef();
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.varType = object.varType ?? 0;
    message.internalType = object.internalType ?? undefined;
    message.variableMode = object.variableMode ?? 0;
    message.isMultiLine = object.isMultiLine ?? false;
    message.isRequired = object.isRequired ?? false;
    message.validationPattern = object.validationPattern ?? "";
    message.selectionItems = object.selectionItems?.map((e) => StepRunnerParamSelectionItem.fromPartial(e)) || [];
    message.isControlField = object.isControlField ?? false;
    message.defaultValue = object.defaultValue ?? "";
    message.fromOldField = object.fromOldField ?? "";
    message.isAdvanced = object.isAdvanced ?? false;
    message.allowInput = object.allowInput ?? false;
    message.visibleExpression = object.visibleExpression ?? "";
    message.replaceVariable = object.replaceVariable ?? false;
    message.defaultHighlightType = object.defaultHighlightType ?? "";
    message.skipEval = object.skipEval ?? false;
    message.skipLogContent = object.skipLogContent ?? false;
    message.validForList = object.validForList?.map((e) => e) || [];
    message.invalidForList = object.invalidForList?.map((e) => e) || [];
    return message;
  },
};

function createBaseStepRunnerOutputParamDef(): StepRunnerOutputParamDef {
  return {
    key: "",
    name: "",
    description: "",
    varType: 0,
    isAdvanced: false,
    visibleExpression: "",
    customTypeName: "",
    skipLogContent: false,
    validForList: [],
    invalidForList: [],
  };
}

export const StepRunnerOutputParamDef: MessageFns<StepRunnerOutputParamDef> = {
  encode(message: StepRunnerOutputParamDef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.varType !== 0) {
      writer.uint32(32).int32(message.varType);
    }
    if (message.isAdvanced !== false) {
      writer.uint32(40).bool(message.isAdvanced);
    }
    if (message.visibleExpression !== "") {
      writer.uint32(50).string(message.visibleExpression);
    }
    if (message.customTypeName !== "") {
      writer.uint32(58).string(message.customTypeName);
    }
    if (message.skipLogContent !== false) {
      writer.uint32(64).bool(message.skipLogContent);
    }
    for (const v of message.validForList) {
      writer.uint32(74).string(v!);
    }
    for (const v of message.invalidForList) {
      writer.uint32(82).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepRunnerOutputParamDef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepRunnerOutputParamDef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.varType = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isAdvanced = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.visibleExpression = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.customTypeName = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.skipLogContent = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.validForList.push(reader.string());
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.invalidForList.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepRunnerOutputParamDef {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      varType: isSet(object.varType) ? globalThis.Number(object.varType) : 0,
      isAdvanced: isSet(object.isAdvanced) ? globalThis.Boolean(object.isAdvanced) : false,
      visibleExpression: isSet(object.visibleExpression) ? globalThis.String(object.visibleExpression) : "",
      customTypeName: isSet(object.customTypeName) ? globalThis.String(object.customTypeName) : "",
      skipLogContent: isSet(object.skipLogContent) ? globalThis.Boolean(object.skipLogContent) : false,
      validForList: globalThis.Array.isArray(object?.validForList)
        ? object.validForList.map((e: any) => globalThis.String(e))
        : [],
      invalidForList: globalThis.Array.isArray(object?.invalidForList)
        ? object.invalidForList.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: StepRunnerOutputParamDef): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.varType !== 0) {
      obj.varType = Math.round(message.varType);
    }
    if (message.isAdvanced !== false) {
      obj.isAdvanced = message.isAdvanced;
    }
    if (message.visibleExpression !== "") {
      obj.visibleExpression = message.visibleExpression;
    }
    if (message.customTypeName !== "") {
      obj.customTypeName = message.customTypeName;
    }
    if (message.skipLogContent !== false) {
      obj.skipLogContent = message.skipLogContent;
    }
    if (message.validForList?.length) {
      obj.validForList = message.validForList;
    }
    if (message.invalidForList?.length) {
      obj.invalidForList = message.invalidForList;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepRunnerOutputParamDef>, I>>(base?: I): StepRunnerOutputParamDef {
    return StepRunnerOutputParamDef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepRunnerOutputParamDef>, I>>(object: I): StepRunnerOutputParamDef {
    const message = createBaseStepRunnerOutputParamDef();
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.varType = object.varType ?? 0;
    message.isAdvanced = object.isAdvanced ?? false;
    message.visibleExpression = object.visibleExpression ?? "";
    message.customTypeName = object.customTypeName ?? "";
    message.skipLogContent = object.skipLogContent ?? false;
    message.validForList = object.validForList?.map((e) => e) || [];
    message.invalidForList = object.invalidForList?.map((e) => e) || [];
    return message;
  },
};

function createBaseStepRunnerItem(): StepRunnerItem {
  return {
    key: "",
    name: "",
    description: "",
    icon: "",
    category: "",
    secondaryCategories: [],
    keywords: [],
    supportedParams: [],
    subItems: [],
    stepType: "",
    inputParamDefs: [],
    outputParamDefs: [],
  };
}

export const StepRunnerItem: MessageFns<StepRunnerItem> = {
  encode(message: StepRunnerItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.icon !== "") {
      writer.uint32(34).string(message.icon);
    }
    if (message.category !== "") {
      writer.uint32(42).string(message.category);
    }
    for (const v of message.secondaryCategories) {
      writer.uint32(50).string(v!);
    }
    for (const v of message.keywords) {
      writer.uint32(58).string(v!);
    }
    for (const v of message.supportedParams) {
      writer.uint32(66).string(v!);
    }
    for (const v of message.subItems) {
      StepRunnerSubItem.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.stepType !== "") {
      writer.uint32(82).string(message.stepType);
    }
    for (const v of message.inputParamDefs) {
      StepRunnerInputParamDef.encode(v!, writer.uint32(90).fork()).join();
    }
    for (const v of message.outputParamDefs) {
      StepRunnerOutputParamDef.encode(v!, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepRunnerItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepRunnerItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.category = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.secondaryCategories.push(reader.string());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.keywords.push(reader.string());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.supportedParams.push(reader.string());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.subItems.push(StepRunnerSubItem.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.stepType = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.inputParamDefs.push(StepRunnerInputParamDef.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.outputParamDefs.push(StepRunnerOutputParamDef.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepRunnerItem {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
      category: isSet(object.category) ? globalThis.String(object.category) : "",
      secondaryCategories: globalThis.Array.isArray(object?.secondaryCategories)
        ? object.secondaryCategories.map((e: any) => globalThis.String(e))
        : [],
      keywords: globalThis.Array.isArray(object?.keywords) ? object.keywords.map((e: any) => globalThis.String(e)) : [],
      supportedParams: globalThis.Array.isArray(object?.supportedParams)
        ? object.supportedParams.map((e: any) => globalThis.String(e))
        : [],
      subItems: globalThis.Array.isArray(object?.subItems)
        ? object.subItems.map((e: any) => StepRunnerSubItem.fromJSON(e))
        : [],
      stepType: isSet(object.stepType) ? globalThis.String(object.stepType) : "",
      inputParamDefs: globalThis.Array.isArray(object?.inputParamDefs)
        ? object.inputParamDefs.map((e: any) => StepRunnerInputParamDef.fromJSON(e))
        : [],
      outputParamDefs: globalThis.Array.isArray(object?.outputParamDefs)
        ? object.outputParamDefs.map((e: any) => StepRunnerOutputParamDef.fromJSON(e))
        : [],
    };
  },

  toJSON(message: StepRunnerItem): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    if (message.category !== "") {
      obj.category = message.category;
    }
    if (message.secondaryCategories?.length) {
      obj.secondaryCategories = message.secondaryCategories;
    }
    if (message.keywords?.length) {
      obj.keywords = message.keywords;
    }
    if (message.supportedParams?.length) {
      obj.supportedParams = message.supportedParams;
    }
    if (message.subItems?.length) {
      obj.subItems = message.subItems.map((e) => StepRunnerSubItem.toJSON(e));
    }
    if (message.stepType !== "") {
      obj.stepType = message.stepType;
    }
    if (message.inputParamDefs?.length) {
      obj.inputParamDefs = message.inputParamDefs.map((e) => StepRunnerInputParamDef.toJSON(e));
    }
    if (message.outputParamDefs?.length) {
      obj.outputParamDefs = message.outputParamDefs.map((e) => StepRunnerOutputParamDef.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepRunnerItem>, I>>(base?: I): StepRunnerItem {
    return StepRunnerItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepRunnerItem>, I>>(object: I): StepRunnerItem {
    const message = createBaseStepRunnerItem();
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.icon = object.icon ?? "";
    message.category = object.category ?? "";
    message.secondaryCategories = object.secondaryCategories?.map((e) => e) || [];
    message.keywords = object.keywords?.map((e) => e) || [];
    message.supportedParams = object.supportedParams?.map((e) => e) || [];
    message.subItems = object.subItems?.map((e) => StepRunnerSubItem.fromPartial(e)) || [];
    message.stepType = object.stepType ?? "";
    message.inputParamDefs = object.inputParamDefs?.map((e) => StepRunnerInputParamDef.fromPartial(e)) || [];
    message.outputParamDefs = object.outputParamDefs?.map((e) => StepRunnerOutputParamDef.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetStepRunnersResponse(): GetStepRunnersResponse {
  return { count: 0, items: [] };
}

export const GetStepRunnersResponse: MessageFns<GetStepRunnersResponse> = {
  encode(message: GetStepRunnersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.count !== 0) {
      writer.uint32(8).int32(message.count);
    }
    for (const v of message.items) {
      StepRunnerItem.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStepRunnersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStepRunnersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.count = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.items.push(StepRunnerItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStepRunnersResponse {
    return {
      count: isSet(object.count) ? globalThis.Number(object.count) : 0,
      items: globalThis.Array.isArray(object?.items) ? object.items.map((e: any) => StepRunnerItem.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetStepRunnersResponse): unknown {
    const obj: any = {};
    if (message.count !== 0) {
      obj.count = Math.round(message.count);
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => StepRunnerItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStepRunnersResponse>, I>>(base?: I): GetStepRunnersResponse {
    return GetStepRunnersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStepRunnersResponse>, I>>(object: I): GetStepRunnersResponse {
    const message = createBaseGetStepRunnersResponse();
    message.count = object.count ?? 0;
    message.items = object.items?.map((e) => StepRunnerItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStepSchema(): StepSchema {
  return { stepType: "", title: "", supportedParams: [] };
}

export const StepSchema: MessageFns<StepSchema> = {
  encode(message: StepSchema, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stepType !== "") {
      writer.uint32(10).string(message.stepType);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    for (const v of message.supportedParams) {
      writer.uint32(26).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepSchema {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepSchema();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stepType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.supportedParams.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepSchema {
    return {
      stepType: isSet(object.stepType) ? globalThis.String(object.stepType) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      supportedParams: globalThis.Array.isArray(object?.supportedParams)
        ? object.supportedParams.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: StepSchema): unknown {
    const obj: any = {};
    if (message.stepType !== "") {
      obj.stepType = message.stepType;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.supportedParams?.length) {
      obj.supportedParams = message.supportedParams;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepSchema>, I>>(base?: I): StepSchema {
    return StepSchema.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepSchema>, I>>(object: I): StepSchema {
    const message = createBaseStepSchema();
    message.stepType = object.stepType ?? "";
    message.title = object.title ?? "";
    message.supportedParams = object.supportedParams?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetStepSchemasResponse(): GetStepSchemasResponse {
  return { schemas: [] };
}

export const GetStepSchemasResponse: MessageFns<GetStepSchemasResponse> = {
  encode(message: GetStepSchemasResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.schemas) {
      StepSchema.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetStepSchemasResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetStepSchemasResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.schemas.push(StepSchema.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetStepSchemasResponse {
    return {
      schemas: globalThis.Array.isArray(object?.schemas) ? object.schemas.map((e: any) => StepSchema.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetStepSchemasResponse): unknown {
    const obj: any = {};
    if (message.schemas?.length) {
      obj.schemas = message.schemas.map((e) => StepSchema.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetStepSchemasResponse>, I>>(base?: I): GetStepSchemasResponse {
    return GetStepSchemasResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetStepSchemasResponse>, I>>(object: I): GetStepSchemasResponse {
    const message = createBaseGetStepSchemasResponse();
    message.schemas = object.schemas?.map((e) => StepSchema.fromPartial(e)) || [];
    return message;
  },
};

function createBaseValidateActionRequest(): ValidateActionRequest {
  return { actionId: "", context: undefined };
}

export const ValidateActionRequest: MessageFns<ValidateActionRequest> = {
  encode(message: ValidateActionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.actionId !== "") {
      writer.uint32(10).string(message.actionId);
    }
    if (message.context !== undefined) {
      RequestContext.encode(message.context, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateActionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateActionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.actionId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.context = RequestContext.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateActionRequest {
    return {
      actionId: isSet(object.actionId) ? globalThis.String(object.actionId) : "",
      context: isSet(object.context) ? RequestContext.fromJSON(object.context) : undefined,
    };
  },

  toJSON(message: ValidateActionRequest): unknown {
    const obj: any = {};
    if (message.actionId !== "") {
      obj.actionId = message.actionId;
    }
    if (message.context !== undefined) {
      obj.context = RequestContext.toJSON(message.context);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateActionRequest>, I>>(base?: I): ValidateActionRequest {
    return ValidateActionRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateActionRequest>, I>>(object: I): ValidateActionRequest {
    const message = createBaseValidateActionRequest();
    message.actionId = object.actionId ?? "";
    message.context = (object.context !== undefined && object.context !== null)
      ? RequestContext.fromPartial(object.context)
      : undefined;
    return message;
  },
};

function createBaseValidateActionResponse(): ValidateActionResponse {
  return { issues: [] };
}

export const ValidateActionResponse: MessageFns<ValidateActionResponse> = {
  encode(message: ValidateActionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.issues) {
      ValidationIssue.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidateActionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidateActionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.issues.push(ValidationIssue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidateActionResponse {
    return {
      issues: globalThis.Array.isArray(object?.issues)
        ? object.issues.map((e: any) => ValidationIssue.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ValidateActionResponse): unknown {
    const obj: any = {};
    if (message.issues?.length) {
      obj.issues = message.issues.map((e) => ValidationIssue.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidateActionResponse>, I>>(base?: I): ValidateActionResponse {
    return ValidateActionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidateActionResponse>, I>>(object: I): ValidateActionResponse {
    const message = createBaseValidateActionResponse();
    message.issues = object.issues?.map((e) => ValidationIssue.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
