// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v3.19.1
// source: common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

/**
 * Web/editor transport for steps and variables (camelCase JSON). Persisted native X program body is
 * x_action_program.proto (XStepData, XVariableData, XActionData) with PascalCase json_name — not a second on-disk model.
 *
 * Quicker.Domain.Actions.X.Storage.InputParamInfo — variable exposed as action input parameter.
 * Enum fields store C# underlying int (Quicker.Public.Forms.InputMethod, ParamVariableMode, TextToolsReplaceMode).
 */
export interface ActionVariableInputParamInfo {
  inputMethod: number;
  selectionItems: string;
  onlyUseSelect: boolean;
  isRequired: boolean;
  validationPattern: string;
  variableMode: number;
  textTools: string;
  replaceMode: number;
  isAdvanced: boolean;
  allowInput: boolean;
  multiLine: boolean;
  visibleExpression: string;
  skipEval: boolean;
}

/** Quicker.Domain.Actions.X.Storage.OutputParamInfo */
export interface ActionVariableOutputParamInfo {
  visibleExpression: string;
}

/**
 * Quicker.Domain.Actions.X.Storage.TableField + Quicker.Public.Forms.FormField base persisted fields.
 * DefaultValue on TableField is string in JSON (specializes FormField object slot).
 */
export interface ActionTableField {
  fieldKey: string;
  label: string;
  helpText: string;
  quickerVarType: number;
  isKey: boolean;
  isMutex: boolean;
  isUnique: boolean;
  isSelectFlag: boolean;
  allowNull: boolean;
  autoIncrement: boolean;
  autoIncrementSeed: number;
  autoIncrementStep: number;
  typeName: string;
  formatString: string;
  isDisabled: boolean;
  defaultValue: string;
  inputHeight: number;
  showInList: boolean;
  editorType: string;
  computeExpression: string;
  dictVarType?: number | undefined;
  helpLink: string;
  inputMethod: number;
  selectionItems: string;
  isRequired: boolean;
  minValue: string;
  maxValue: string;
  pattern: string;
  inputWidth: string;
  maxLength: number;
  imeState: string;
  textTools: string;
  extraSettings: string;
  visibleExpression: string;
  columnWidth: number;
  onlyDate: boolean;
  readOnly: boolean;
  group: string;
}

/** Quicker.Domain.Actions.X.Storage.TableDef */
export interface ActionTableDef {
  fields: ActionTableField[];
}

/**
 * Quicker.Domain.Actions.X.Storage.ActionVariable — action-scoped variable definition.
 * var_type uses Quicker.Public.Actions.VarType numeric values (Text=0, Number=1, Boolean=2, …).
 */
export interface ActionVariable {
  /** Stable id for editor / transport (row identity); not renamed when Key changes in some flows. */
  id: string;
  /** Variable name (Key). */
  key: string;
  varType: number;
  defaultValue: string;
  desc: string;
  isLocked: boolean;
  saveState: boolean;
  isInput: boolean;
  isOutput: boolean;
  paramName: string;
  group: string;
  customType: string;
  inputParamInfo?: ActionVariableInputParamInfo | undefined;
  outputParamInfo?: ActionVariableOutputParamInfo | undefined;
  tableDef?: ActionTableDef | undefined;
}

export interface StepItem {
  id: string;
  stepType: string;
  title: string;
  parentId: string;
}

export interface StepParam {
  name: string;
  value: string;
}

export interface ActionStepParam {
  varKey: string;
  value: string;
  /** Agent wire JSON external file reference (files/…). */
  file?: string;
}

export interface ActionStep {
  stepRunnerKey: string;
  inputParams: { [key: string]: ActionStepParam };
  outputParams: { [key: string]: string };
  ifSteps: ActionStep[];
  elseSteps: ActionStep[];
  note: string;
  disabled: boolean;
  collapsed: boolean;
  delayMs: number;
  stepId: string;
}

export interface ActionStep_InputParamsEntry {
  key: string;
  value?: ActionStepParam | undefined;
}

export interface ActionStep_OutputParamsEntry {
  key: string;
  value: string;
}

/**
 * One row in the action sub program list for Web GetAction.
 * kind: 0 unspecified, 1 internal, 2 global library link, 3 shared / template reference.
 */
export interface ActionSubProgram {
  id: string;
  name: string;
  description: string;
  icon: string;
  kind: number;
  /** Summary for list UI (may mirror len(steps) / len(variables)). */
  stepCount: number;
  /** Summary for list UI. */
  variableCount: number;
  /**
   * Variables from nested IXProgram body (XSubProgramData.Variables), used by Web to edit
   * sys:subprogram var:* step params like desktop ActionStepEditorWindow.
   */
  variables: ActionVariable[];
  /** Steps from nested IXProgram body (XSubProgramData.Steps); seeds Web sub program tab when no session snapshot. */
  steps: ActionStep[];
  /** Nested sub programs (XSubProgramData.SubPrograms), same shape as root action.sub_programs. */
  subPrograms: ActionSubProgram[];
}

export interface ValidationIssue {
  code: string;
  message: string;
  targetPath: string;
  severity: string;
}

export interface CommandDiffSummary {
  title: string;
  changedPaths: string[];
}

export interface RequestContext {
  operatorId: string;
  traceId: string;
}

function createBaseActionVariableInputParamInfo(): ActionVariableInputParamInfo {
  return {
    inputMethod: 0,
    selectionItems: "",
    onlyUseSelect: false,
    isRequired: false,
    validationPattern: "",
    variableMode: 0,
    textTools: "",
    replaceMode: 0,
    isAdvanced: false,
    allowInput: false,
    multiLine: false,
    visibleExpression: "",
    skipEval: false,
  };
}

export const ActionVariableInputParamInfo: MessageFns<ActionVariableInputParamInfo> = {
  encode(message: ActionVariableInputParamInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.inputMethod !== 0) {
      writer.uint32(8).int32(message.inputMethod);
    }
    if (message.selectionItems !== "") {
      writer.uint32(18).string(message.selectionItems);
    }
    if (message.onlyUseSelect !== false) {
      writer.uint32(24).bool(message.onlyUseSelect);
    }
    if (message.isRequired !== false) {
      writer.uint32(32).bool(message.isRequired);
    }
    if (message.validationPattern !== "") {
      writer.uint32(42).string(message.validationPattern);
    }
    if (message.variableMode !== 0) {
      writer.uint32(48).int32(message.variableMode);
    }
    if (message.textTools !== "") {
      writer.uint32(58).string(message.textTools);
    }
    if (message.replaceMode !== 0) {
      writer.uint32(64).int32(message.replaceMode);
    }
    if (message.isAdvanced !== false) {
      writer.uint32(72).bool(message.isAdvanced);
    }
    if (message.allowInput !== false) {
      writer.uint32(80).bool(message.allowInput);
    }
    if (message.multiLine !== false) {
      writer.uint32(88).bool(message.multiLine);
    }
    if (message.visibleExpression !== "") {
      writer.uint32(98).string(message.visibleExpression);
    }
    if (message.skipEval !== false) {
      writer.uint32(104).bool(message.skipEval);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionVariableInputParamInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionVariableInputParamInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.inputMethod = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.selectionItems = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.onlyUseSelect = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.isRequired = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.validationPattern = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.variableMode = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.textTools = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.replaceMode = reader.int32();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isAdvanced = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.allowInput = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.multiLine = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.visibleExpression = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.skipEval = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionVariableInputParamInfo {
    return {
      inputMethod: isSet(object.inputMethod) ? globalThis.Number(object.inputMethod) : 0,
      selectionItems: isSet(object.selectionItems) ? globalThis.String(object.selectionItems) : "",
      onlyUseSelect: isSet(object.onlyUseSelect) ? globalThis.Boolean(object.onlyUseSelect) : false,
      isRequired: isSet(object.isRequired) ? globalThis.Boolean(object.isRequired) : false,
      validationPattern: isSet(object.validationPattern) ? globalThis.String(object.validationPattern) : "",
      variableMode: isSet(object.variableMode) ? globalThis.Number(object.variableMode) : 0,
      textTools: isSet(object.textTools) ? globalThis.String(object.textTools) : "",
      replaceMode: isSet(object.replaceMode) ? globalThis.Number(object.replaceMode) : 0,
      isAdvanced: isSet(object.isAdvanced) ? globalThis.Boolean(object.isAdvanced) : false,
      allowInput: isSet(object.allowInput) ? globalThis.Boolean(object.allowInput) : false,
      multiLine: isSet(object.multiLine) ? globalThis.Boolean(object.multiLine) : false,
      visibleExpression: isSet(object.visibleExpression) ? globalThis.String(object.visibleExpression) : "",
      skipEval: isSet(object.skipEval) ? globalThis.Boolean(object.skipEval) : false,
    };
  },

  toJSON(message: ActionVariableInputParamInfo): unknown {
    const obj: any = {};
    if (message.inputMethod !== 0) {
      obj.inputMethod = Math.round(message.inputMethod);
    }
    if (message.selectionItems !== "") {
      obj.selectionItems = message.selectionItems;
    }
    if (message.onlyUseSelect !== false) {
      obj.onlyUseSelect = message.onlyUseSelect;
    }
    if (message.isRequired !== false) {
      obj.isRequired = message.isRequired;
    }
    if (message.validationPattern !== "") {
      obj.validationPattern = message.validationPattern;
    }
    if (message.variableMode !== 0) {
      obj.variableMode = Math.round(message.variableMode);
    }
    if (message.textTools !== "") {
      obj.textTools = message.textTools;
    }
    if (message.replaceMode !== 0) {
      obj.replaceMode = Math.round(message.replaceMode);
    }
    if (message.isAdvanced !== false) {
      obj.isAdvanced = message.isAdvanced;
    }
    if (message.allowInput !== false) {
      obj.allowInput = message.allowInput;
    }
    if (message.multiLine !== false) {
      obj.multiLine = message.multiLine;
    }
    if (message.visibleExpression !== "") {
      obj.visibleExpression = message.visibleExpression;
    }
    if (message.skipEval !== false) {
      obj.skipEval = message.skipEval;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionVariableInputParamInfo>, I>>(base?: I): ActionVariableInputParamInfo {
    return ActionVariableInputParamInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionVariableInputParamInfo>, I>>(object: I): ActionVariableInputParamInfo {
    const message = createBaseActionVariableInputParamInfo();
    message.inputMethod = object.inputMethod ?? 0;
    message.selectionItems = object.selectionItems ?? "";
    message.onlyUseSelect = object.onlyUseSelect ?? false;
    message.isRequired = object.isRequired ?? false;
    message.validationPattern = object.validationPattern ?? "";
    message.variableMode = object.variableMode ?? 0;
    message.textTools = object.textTools ?? "";
    message.replaceMode = object.replaceMode ?? 0;
    message.isAdvanced = object.isAdvanced ?? false;
    message.allowInput = object.allowInput ?? false;
    message.multiLine = object.multiLine ?? false;
    message.visibleExpression = object.visibleExpression ?? "";
    message.skipEval = object.skipEval ?? false;
    return message;
  },
};

function createBaseActionVariableOutputParamInfo(): ActionVariableOutputParamInfo {
  return { visibleExpression: "" };
}

export const ActionVariableOutputParamInfo: MessageFns<ActionVariableOutputParamInfo> = {
  encode(message: ActionVariableOutputParamInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.visibleExpression !== "") {
      writer.uint32(10).string(message.visibleExpression);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionVariableOutputParamInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionVariableOutputParamInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.visibleExpression = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionVariableOutputParamInfo {
    return { visibleExpression: isSet(object.visibleExpression) ? globalThis.String(object.visibleExpression) : "" };
  },

  toJSON(message: ActionVariableOutputParamInfo): unknown {
    const obj: any = {};
    if (message.visibleExpression !== "") {
      obj.visibleExpression = message.visibleExpression;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionVariableOutputParamInfo>, I>>(base?: I): ActionVariableOutputParamInfo {
    return ActionVariableOutputParamInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionVariableOutputParamInfo>, I>>(
    object: I,
  ): ActionVariableOutputParamInfo {
    const message = createBaseActionVariableOutputParamInfo();
    message.visibleExpression = object.visibleExpression ?? "";
    return message;
  },
};

function createBaseActionTableField(): ActionTableField {
  return {
    fieldKey: "",
    label: "",
    helpText: "",
    quickerVarType: 0,
    isKey: false,
    isMutex: false,
    isUnique: false,
    isSelectFlag: false,
    allowNull: false,
    autoIncrement: false,
    autoIncrementSeed: 0,
    autoIncrementStep: 0,
    typeName: "",
    formatString: "",
    isDisabled: false,
    defaultValue: "",
    inputHeight: 0,
    showInList: false,
    editorType: "",
    computeExpression: "",
    dictVarType: undefined,
    helpLink: "",
    inputMethod: 0,
    selectionItems: "",
    isRequired: false,
    minValue: "",
    maxValue: "",
    pattern: "",
    inputWidth: "",
    maxLength: 0,
    imeState: "",
    textTools: "",
    extraSettings: "",
    visibleExpression: "",
    columnWidth: 0,
    onlyDate: false,
    readOnly: false,
    group: "",
  };
}

export const ActionTableField: MessageFns<ActionTableField> = {
  encode(message: ActionTableField, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fieldKey !== "") {
      writer.uint32(10).string(message.fieldKey);
    }
    if (message.label !== "") {
      writer.uint32(18).string(message.label);
    }
    if (message.helpText !== "") {
      writer.uint32(26).string(message.helpText);
    }
    if (message.quickerVarType !== 0) {
      writer.uint32(32).int32(message.quickerVarType);
    }
    if (message.isKey !== false) {
      writer.uint32(40).bool(message.isKey);
    }
    if (message.isMutex !== false) {
      writer.uint32(48).bool(message.isMutex);
    }
    if (message.isUnique !== false) {
      writer.uint32(56).bool(message.isUnique);
    }
    if (message.isSelectFlag !== false) {
      writer.uint32(64).bool(message.isSelectFlag);
    }
    if (message.allowNull !== false) {
      writer.uint32(72).bool(message.allowNull);
    }
    if (message.autoIncrement !== false) {
      writer.uint32(80).bool(message.autoIncrement);
    }
    if (message.autoIncrementSeed !== 0) {
      writer.uint32(88).int32(message.autoIncrementSeed);
    }
    if (message.autoIncrementStep !== 0) {
      writer.uint32(96).int32(message.autoIncrementStep);
    }
    if (message.typeName !== "") {
      writer.uint32(106).string(message.typeName);
    }
    if (message.formatString !== "") {
      writer.uint32(114).string(message.formatString);
    }
    if (message.isDisabled !== false) {
      writer.uint32(120).bool(message.isDisabled);
    }
    if (message.defaultValue !== "") {
      writer.uint32(130).string(message.defaultValue);
    }
    if (message.inputHeight !== 0) {
      writer.uint32(137).double(message.inputHeight);
    }
    if (message.showInList !== false) {
      writer.uint32(144).bool(message.showInList);
    }
    if (message.editorType !== "") {
      writer.uint32(154).string(message.editorType);
    }
    if (message.computeExpression !== "") {
      writer.uint32(162).string(message.computeExpression);
    }
    if (message.dictVarType !== undefined) {
      writer.uint32(168).int32(message.dictVarType);
    }
    if (message.helpLink !== "") {
      writer.uint32(178).string(message.helpLink);
    }
    if (message.inputMethod !== 0) {
      writer.uint32(184).int32(message.inputMethod);
    }
    if (message.selectionItems !== "") {
      writer.uint32(194).string(message.selectionItems);
    }
    if (message.isRequired !== false) {
      writer.uint32(200).bool(message.isRequired);
    }
    if (message.minValue !== "") {
      writer.uint32(210).string(message.minValue);
    }
    if (message.maxValue !== "") {
      writer.uint32(218).string(message.maxValue);
    }
    if (message.pattern !== "") {
      writer.uint32(226).string(message.pattern);
    }
    if (message.inputWidth !== "") {
      writer.uint32(234).string(message.inputWidth);
    }
    if (message.maxLength !== 0) {
      writer.uint32(240).int32(message.maxLength);
    }
    if (message.imeState !== "") {
      writer.uint32(250).string(message.imeState);
    }
    if (message.textTools !== "") {
      writer.uint32(258).string(message.textTools);
    }
    if (message.extraSettings !== "") {
      writer.uint32(266).string(message.extraSettings);
    }
    if (message.visibleExpression !== "") {
      writer.uint32(274).string(message.visibleExpression);
    }
    if (message.columnWidth !== 0) {
      writer.uint32(281).double(message.columnWidth);
    }
    if (message.onlyDate !== false) {
      writer.uint32(288).bool(message.onlyDate);
    }
    if (message.readOnly !== false) {
      writer.uint32(296).bool(message.readOnly);
    }
    if (message.group !== "") {
      writer.uint32(306).string(message.group);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionTableField {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionTableField();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fieldKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.helpText = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.quickerVarType = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isKey = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isMutex = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isUnique = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isSelectFlag = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.allowNull = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.autoIncrement = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.autoIncrementSeed = reader.int32();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.autoIncrementStep = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.typeName = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.formatString = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.isDisabled = reader.bool();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.defaultValue = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 137) {
            break;
          }

          message.inputHeight = reader.double();
          continue;
        }
        case 18: {
          if (tag !== 144) {
            break;
          }

          message.showInList = reader.bool();
          continue;
        }
        case 19: {
          if (tag !== 154) {
            break;
          }

          message.editorType = reader.string();
          continue;
        }
        case 20: {
          if (tag !== 162) {
            break;
          }

          message.computeExpression = reader.string();
          continue;
        }
        case 21: {
          if (tag !== 168) {
            break;
          }

          message.dictVarType = reader.int32();
          continue;
        }
        case 22: {
          if (tag !== 178) {
            break;
          }

          message.helpLink = reader.string();
          continue;
        }
        case 23: {
          if (tag !== 184) {
            break;
          }

          message.inputMethod = reader.int32();
          continue;
        }
        case 24: {
          if (tag !== 194) {
            break;
          }

          message.selectionItems = reader.string();
          continue;
        }
        case 25: {
          if (tag !== 200) {
            break;
          }

          message.isRequired = reader.bool();
          continue;
        }
        case 26: {
          if (tag !== 210) {
            break;
          }

          message.minValue = reader.string();
          continue;
        }
        case 27: {
          if (tag !== 218) {
            break;
          }

          message.maxValue = reader.string();
          continue;
        }
        case 28: {
          if (tag !== 226) {
            break;
          }

          message.pattern = reader.string();
          continue;
        }
        case 29: {
          if (tag !== 234) {
            break;
          }

          message.inputWidth = reader.string();
          continue;
        }
        case 30: {
          if (tag !== 240) {
            break;
          }

          message.maxLength = reader.int32();
          continue;
        }
        case 31: {
          if (tag !== 250) {
            break;
          }

          message.imeState = reader.string();
          continue;
        }
        case 32: {
          if (tag !== 258) {
            break;
          }

          message.textTools = reader.string();
          continue;
        }
        case 33: {
          if (tag !== 266) {
            break;
          }

          message.extraSettings = reader.string();
          continue;
        }
        case 34: {
          if (tag !== 274) {
            break;
          }

          message.visibleExpression = reader.string();
          continue;
        }
        case 35: {
          if (tag !== 281) {
            break;
          }

          message.columnWidth = reader.double();
          continue;
        }
        case 36: {
          if (tag !== 288) {
            break;
          }

          message.onlyDate = reader.bool();
          continue;
        }
        case 37: {
          if (tag !== 296) {
            break;
          }

          message.readOnly = reader.bool();
          continue;
        }
        case 38: {
          if (tag !== 306) {
            break;
          }

          message.group = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionTableField {
    return {
      fieldKey: isSet(object.fieldKey) ? globalThis.String(object.fieldKey) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      helpText: isSet(object.helpText) ? globalThis.String(object.helpText) : "",
      quickerVarType: isSet(object.quickerVarType) ? globalThis.Number(object.quickerVarType) : 0,
      isKey: isSet(object.isKey) ? globalThis.Boolean(object.isKey) : false,
      isMutex: isSet(object.isMutex) ? globalThis.Boolean(object.isMutex) : false,
      isUnique: isSet(object.isUnique) ? globalThis.Boolean(object.isUnique) : false,
      isSelectFlag: isSet(object.isSelectFlag) ? globalThis.Boolean(object.isSelectFlag) : false,
      allowNull: isSet(object.allowNull) ? globalThis.Boolean(object.allowNull) : false,
      autoIncrement: isSet(object.autoIncrement) ? globalThis.Boolean(object.autoIncrement) : false,
      autoIncrementSeed: isSet(object.autoIncrementSeed) ? globalThis.Number(object.autoIncrementSeed) : 0,
      autoIncrementStep: isSet(object.autoIncrementStep) ? globalThis.Number(object.autoIncrementStep) : 0,
      typeName: isSet(object.typeName) ? globalThis.String(object.typeName) : "",
      formatString: isSet(object.formatString) ? globalThis.String(object.formatString) : "",
      isDisabled: isSet(object.isDisabled) ? globalThis.Boolean(object.isDisabled) : false,
      defaultValue: isSet(object.defaultValue) ? globalThis.String(object.defaultValue) : "",
      inputHeight: isSet(object.inputHeight) ? globalThis.Number(object.inputHeight) : 0,
      showInList: isSet(object.showInList) ? globalThis.Boolean(object.showInList) : false,
      editorType: isSet(object.editorType) ? globalThis.String(object.editorType) : "",
      computeExpression: isSet(object.computeExpression) ? globalThis.String(object.computeExpression) : "",
      dictVarType: isSet(object.dictVarType) ? globalThis.Number(object.dictVarType) : undefined,
      helpLink: isSet(object.helpLink) ? globalThis.String(object.helpLink) : "",
      inputMethod: isSet(object.inputMethod) ? globalThis.Number(object.inputMethod) : 0,
      selectionItems: isSet(object.selectionItems) ? globalThis.String(object.selectionItems) : "",
      isRequired: isSet(object.isRequired) ? globalThis.Boolean(object.isRequired) : false,
      minValue: isSet(object.minValue) ? globalThis.String(object.minValue) : "",
      maxValue: isSet(object.maxValue) ? globalThis.String(object.maxValue) : "",
      pattern: isSet(object.pattern) ? globalThis.String(object.pattern) : "",
      inputWidth: isSet(object.inputWidth) ? globalThis.String(object.inputWidth) : "",
      maxLength: isSet(object.maxLength) ? globalThis.Number(object.maxLength) : 0,
      imeState: isSet(object.imeState) ? globalThis.String(object.imeState) : "",
      textTools: isSet(object.textTools) ? globalThis.String(object.textTools) : "",
      extraSettings: isSet(object.extraSettings) ? globalThis.String(object.extraSettings) : "",
      visibleExpression: isSet(object.visibleExpression) ? globalThis.String(object.visibleExpression) : "",
      columnWidth: isSet(object.columnWidth) ? globalThis.Number(object.columnWidth) : 0,
      onlyDate: isSet(object.onlyDate) ? globalThis.Boolean(object.onlyDate) : false,
      readOnly: isSet(object.readOnly) ? globalThis.Boolean(object.readOnly) : false,
      group: isSet(object.group) ? globalThis.String(object.group) : "",
    };
  },

  toJSON(message: ActionTableField): unknown {
    const obj: any = {};
    if (message.fieldKey !== "") {
      obj.fieldKey = message.fieldKey;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.helpText !== "") {
      obj.helpText = message.helpText;
    }
    if (message.quickerVarType !== 0) {
      obj.quickerVarType = Math.round(message.quickerVarType);
    }
    if (message.isKey !== false) {
      obj.isKey = message.isKey;
    }
    if (message.isMutex !== false) {
      obj.isMutex = message.isMutex;
    }
    if (message.isUnique !== false) {
      obj.isUnique = message.isUnique;
    }
    if (message.isSelectFlag !== false) {
      obj.isSelectFlag = message.isSelectFlag;
    }
    if (message.allowNull !== false) {
      obj.allowNull = message.allowNull;
    }
    if (message.autoIncrement !== false) {
      obj.autoIncrement = message.autoIncrement;
    }
    if (message.autoIncrementSeed !== 0) {
      obj.autoIncrementSeed = Math.round(message.autoIncrementSeed);
    }
    if (message.autoIncrementStep !== 0) {
      obj.autoIncrementStep = Math.round(message.autoIncrementStep);
    }
    if (message.typeName !== "") {
      obj.typeName = message.typeName;
    }
    if (message.formatString !== "") {
      obj.formatString = message.formatString;
    }
    if (message.isDisabled !== false) {
      obj.isDisabled = message.isDisabled;
    }
    if (message.defaultValue !== "") {
      obj.defaultValue = message.defaultValue;
    }
    if (message.inputHeight !== 0) {
      obj.inputHeight = message.inputHeight;
    }
    if (message.showInList !== false) {
      obj.showInList = message.showInList;
    }
    if (message.editorType !== "") {
      obj.editorType = message.editorType;
    }
    if (message.computeExpression !== "") {
      obj.computeExpression = message.computeExpression;
    }
    if (message.dictVarType !== undefined) {
      obj.dictVarType = Math.round(message.dictVarType);
    }
    if (message.helpLink !== "") {
      obj.helpLink = message.helpLink;
    }
    if (message.inputMethod !== 0) {
      obj.inputMethod = Math.round(message.inputMethod);
    }
    if (message.selectionItems !== "") {
      obj.selectionItems = message.selectionItems;
    }
    if (message.isRequired !== false) {
      obj.isRequired = message.isRequired;
    }
    if (message.minValue !== "") {
      obj.minValue = message.minValue;
    }
    if (message.maxValue !== "") {
      obj.maxValue = message.maxValue;
    }
    if (message.pattern !== "") {
      obj.pattern = message.pattern;
    }
    if (message.inputWidth !== "") {
      obj.inputWidth = message.inputWidth;
    }
    if (message.maxLength !== 0) {
      obj.maxLength = Math.round(message.maxLength);
    }
    if (message.imeState !== "") {
      obj.imeState = message.imeState;
    }
    if (message.textTools !== "") {
      obj.textTools = message.textTools;
    }
    if (message.extraSettings !== "") {
      obj.extraSettings = message.extraSettings;
    }
    if (message.visibleExpression !== "") {
      obj.visibleExpression = message.visibleExpression;
    }
    if (message.columnWidth !== 0) {
      obj.columnWidth = message.columnWidth;
    }
    if (message.onlyDate !== false) {
      obj.onlyDate = message.onlyDate;
    }
    if (message.readOnly !== false) {
      obj.readOnly = message.readOnly;
    }
    if (message.group !== "") {
      obj.group = message.group;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionTableField>, I>>(base?: I): ActionTableField {
    return ActionTableField.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionTableField>, I>>(object: I): ActionTableField {
    const message = createBaseActionTableField();
    message.fieldKey = object.fieldKey ?? "";
    message.label = object.label ?? "";
    message.helpText = object.helpText ?? "";
    message.quickerVarType = object.quickerVarType ?? 0;
    message.isKey = object.isKey ?? false;
    message.isMutex = object.isMutex ?? false;
    message.isUnique = object.isUnique ?? false;
    message.isSelectFlag = object.isSelectFlag ?? false;
    message.allowNull = object.allowNull ?? false;
    message.autoIncrement = object.autoIncrement ?? false;
    message.autoIncrementSeed = object.autoIncrementSeed ?? 0;
    message.autoIncrementStep = object.autoIncrementStep ?? 0;
    message.typeName = object.typeName ?? "";
    message.formatString = object.formatString ?? "";
    message.isDisabled = object.isDisabled ?? false;
    message.defaultValue = object.defaultValue ?? "";
    message.inputHeight = object.inputHeight ?? 0;
    message.showInList = object.showInList ?? false;
    message.editorType = object.editorType ?? "";
    message.computeExpression = object.computeExpression ?? "";
    message.dictVarType = object.dictVarType ?? undefined;
    message.helpLink = object.helpLink ?? "";
    message.inputMethod = object.inputMethod ?? 0;
    message.selectionItems = object.selectionItems ?? "";
    message.isRequired = object.isRequired ?? false;
    message.minValue = object.minValue ?? "";
    message.maxValue = object.maxValue ?? "";
    message.pattern = object.pattern ?? "";
    message.inputWidth = object.inputWidth ?? "";
    message.maxLength = object.maxLength ?? 0;
    message.imeState = object.imeState ?? "";
    message.textTools = object.textTools ?? "";
    message.extraSettings = object.extraSettings ?? "";
    message.visibleExpression = object.visibleExpression ?? "";
    message.columnWidth = object.columnWidth ?? 0;
    message.onlyDate = object.onlyDate ?? false;
    message.readOnly = object.readOnly ?? false;
    message.group = object.group ?? "";
    return message;
  },
};

function createBaseActionTableDef(): ActionTableDef {
  return { fields: [] };
}

export const ActionTableDef: MessageFns<ActionTableDef> = {
  encode(message: ActionTableDef, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.fields) {
      ActionTableField.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionTableDef {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionTableDef();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fields.push(ActionTableField.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionTableDef {
    return {
      fields: globalThis.Array.isArray(object?.fields)
        ? object.fields.map((e: any) => ActionTableField.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ActionTableDef): unknown {
    const obj: any = {};
    if (message.fields?.length) {
      obj.fields = message.fields.map((e) => ActionTableField.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionTableDef>, I>>(base?: I): ActionTableDef {
    return ActionTableDef.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionTableDef>, I>>(object: I): ActionTableDef {
    const message = createBaseActionTableDef();
    message.fields = object.fields?.map((e) => ActionTableField.fromPartial(e)) || [];
    return message;
  },
};

function createBaseActionVariable(): ActionVariable {
  return {
    id: "",
    key: "",
    varType: 0,
    defaultValue: "",
    desc: "",
    isLocked: false,
    saveState: false,
    isInput: false,
    isOutput: false,
    paramName: "",
    group: "",
    customType: "",
    inputParamInfo: undefined,
    outputParamInfo: undefined,
    tableDef: undefined,
  };
}

export const ActionVariable: MessageFns<ActionVariable> = {
  encode(message: ActionVariable, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.varType !== 0) {
      writer.uint32(24).int32(message.varType);
    }
    if (message.defaultValue !== "") {
      writer.uint32(34).string(message.defaultValue);
    }
    if (message.desc !== "") {
      writer.uint32(42).string(message.desc);
    }
    if (message.isLocked !== false) {
      writer.uint32(48).bool(message.isLocked);
    }
    if (message.saveState !== false) {
      writer.uint32(56).bool(message.saveState);
    }
    if (message.isInput !== false) {
      writer.uint32(64).bool(message.isInput);
    }
    if (message.isOutput !== false) {
      writer.uint32(72).bool(message.isOutput);
    }
    if (message.paramName !== "") {
      writer.uint32(82).string(message.paramName);
    }
    if (message.group !== "") {
      writer.uint32(90).string(message.group);
    }
    if (message.customType !== "") {
      writer.uint32(98).string(message.customType);
    }
    if (message.inputParamInfo !== undefined) {
      ActionVariableInputParamInfo.encode(message.inputParamInfo, writer.uint32(106).fork()).join();
    }
    if (message.outputParamInfo !== undefined) {
      ActionVariableOutputParamInfo.encode(message.outputParamInfo, writer.uint32(114).fork()).join();
    }
    if (message.tableDef !== undefined) {
      ActionTableDef.encode(message.tableDef, writer.uint32(122).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionVariable {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionVariable();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.varType = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.defaultValue = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.desc = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isLocked = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.saveState = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.isInput = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isOutput = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.paramName = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.group = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.customType = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.inputParamInfo = ActionVariableInputParamInfo.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.outputParamInfo = ActionVariableOutputParamInfo.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.tableDef = ActionTableDef.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionVariable {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      varType: isSet(object.varType) ? globalThis.Number(object.varType) : 0,
      defaultValue: isSet(object.defaultValue) ? globalThis.String(object.defaultValue) : "",
      desc: isSet(object.desc) ? globalThis.String(object.desc) : "",
      isLocked: isSet(object.isLocked) ? globalThis.Boolean(object.isLocked) : false,
      saveState: isSet(object.saveState) ? globalThis.Boolean(object.saveState) : false,
      isInput: isSet(object.isInput) ? globalThis.Boolean(object.isInput) : false,
      isOutput: isSet(object.isOutput) ? globalThis.Boolean(object.isOutput) : false,
      paramName: isSet(object.paramName) ? globalThis.String(object.paramName) : "",
      group: isSet(object.group) ? globalThis.String(object.group) : "",
      customType: isSet(object.customType) ? globalThis.String(object.customType) : "",
      inputParamInfo: isSet(object.inputParamInfo)
        ? ActionVariableInputParamInfo.fromJSON(object.inputParamInfo)
        : undefined,
      outputParamInfo: isSet(object.outputParamInfo)
        ? ActionVariableOutputParamInfo.fromJSON(object.outputParamInfo)
        : undefined,
      tableDef: isSet(object.tableDef) ? ActionTableDef.fromJSON(object.tableDef) : undefined,
    };
  },

  toJSON(message: ActionVariable): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.varType !== 0) {
      obj.varType = Math.round(message.varType);
    }
    if (message.defaultValue !== "") {
      obj.defaultValue = message.defaultValue;
    }
    if (message.desc !== "") {
      obj.desc = message.desc;
    }
    if (message.isLocked !== false) {
      obj.isLocked = message.isLocked;
    }
    if (message.saveState !== false) {
      obj.saveState = message.saveState;
    }
    if (message.isInput !== false) {
      obj.isInput = message.isInput;
    }
    if (message.isOutput !== false) {
      obj.isOutput = message.isOutput;
    }
    if (message.paramName !== "") {
      obj.paramName = message.paramName;
    }
    if (message.group !== "") {
      obj.group = message.group;
    }
    if (message.customType !== "") {
      obj.customType = message.customType;
    }
    if (message.inputParamInfo !== undefined) {
      obj.inputParamInfo = ActionVariableInputParamInfo.toJSON(message.inputParamInfo);
    }
    if (message.outputParamInfo !== undefined) {
      obj.outputParamInfo = ActionVariableOutputParamInfo.toJSON(message.outputParamInfo);
    }
    if (message.tableDef !== undefined) {
      obj.tableDef = ActionTableDef.toJSON(message.tableDef);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionVariable>, I>>(base?: I): ActionVariable {
    return ActionVariable.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionVariable>, I>>(object: I): ActionVariable {
    const message = createBaseActionVariable();
    message.id = object.id ?? "";
    message.key = object.key ?? "";
    message.varType = object.varType ?? 0;
    message.defaultValue = object.defaultValue ?? "";
    message.desc = object.desc ?? "";
    message.isLocked = object.isLocked ?? false;
    message.saveState = object.saveState ?? false;
    message.isInput = object.isInput ?? false;
    message.isOutput = object.isOutput ?? false;
    message.paramName = object.paramName ?? "";
    message.group = object.group ?? "";
    message.customType = object.customType ?? "";
    message.inputParamInfo = (object.inputParamInfo !== undefined && object.inputParamInfo !== null)
      ? ActionVariableInputParamInfo.fromPartial(object.inputParamInfo)
      : undefined;
    message.outputParamInfo = (object.outputParamInfo !== undefined && object.outputParamInfo !== null)
      ? ActionVariableOutputParamInfo.fromPartial(object.outputParamInfo)
      : undefined;
    message.tableDef = (object.tableDef !== undefined && object.tableDef !== null)
      ? ActionTableDef.fromPartial(object.tableDef)
      : undefined;
    return message;
  },
};

function createBaseStepItem(): StepItem {
  return { id: "", stepType: "", title: "", parentId: "" };
}

export const StepItem: MessageFns<StepItem> = {
  encode(message: StepItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.stepType !== "") {
      writer.uint32(18).string(message.stepType);
    }
    if (message.title !== "") {
      writer.uint32(26).string(message.title);
    }
    if (message.parentId !== "") {
      writer.uint32(34).string(message.parentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.stepType = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.parentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      stepType: isSet(object.stepType) ? globalThis.String(object.stepType) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      parentId: isSet(object.parentId) ? globalThis.String(object.parentId) : "",
    };
  },

  toJSON(message: StepItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.stepType !== "") {
      obj.stepType = message.stepType;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.parentId !== "") {
      obj.parentId = message.parentId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepItem>, I>>(base?: I): StepItem {
    return StepItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepItem>, I>>(object: I): StepItem {
    const message = createBaseStepItem();
    message.id = object.id ?? "";
    message.stepType = object.stepType ?? "";
    message.title = object.title ?? "";
    message.parentId = object.parentId ?? "";
    return message;
  },
};

function createBaseStepParam(): StepParam {
  return { name: "", value: "" };
}

export const StepParam: MessageFns<StepParam> = {
  encode(message: StepParam, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepParam {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepParam();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepParam {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: StepParam): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepParam>, I>>(base?: I): StepParam {
    return StepParam.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepParam>, I>>(object: I): StepParam {
    const message = createBaseStepParam();
    message.name = object.name ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseActionStepParam(): ActionStepParam {
  return { varKey: "", value: "" };
}

export const ActionStepParam: MessageFns<ActionStepParam> = {
  encode(message: ActionStepParam, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.varKey !== "") {
      writer.uint32(10).string(message.varKey);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionStepParam {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionStepParam();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.varKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionStepParam {
    return {
      varKey: isSet(object.varKey) ? globalThis.String(object.varKey) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
      file: isSet(object.file) ? globalThis.String(object.file) : undefined,
    };
  },

  toJSON(message: ActionStepParam): unknown {
    const obj: any = {};
    if (message.varKey !== "") {
      obj.varKey = message.varKey;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    if (message.file !== undefined && message.file !== "") {
      obj.file = message.file;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionStepParam>, I>>(base?: I): ActionStepParam {
    return ActionStepParam.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionStepParam>, I>>(object: I): ActionStepParam {
    const message = createBaseActionStepParam();
    message.varKey = object.varKey ?? "";
    message.value = object.value ?? "";
    message.file = object.file ?? undefined;
    return message;
  },
};

function createBaseActionStep(): ActionStep {
  return {
    stepRunnerKey: "",
    inputParams: {},
    outputParams: {},
    ifSteps: [],
    elseSteps: [],
    note: "",
    disabled: false,
    collapsed: false,
    delayMs: 0,
    stepId: "",
  };
}

export const ActionStep: MessageFns<ActionStep> = {
  encode(message: ActionStep, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stepRunnerKey !== "") {
      writer.uint32(10).string(message.stepRunnerKey);
    }
    Object.entries(message.inputParams).forEach(([key, value]) => {
      ActionStep_InputParamsEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    Object.entries(message.outputParams).forEach(([key, value]) => {
      ActionStep_OutputParamsEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    for (const v of message.ifSteps) {
      ActionStep.encode(v!, writer.uint32(34).fork()).join();
    }
    for (const v of message.elseSteps) {
      ActionStep.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.note !== "") {
      writer.uint32(50).string(message.note);
    }
    if (message.disabled !== false) {
      writer.uint32(56).bool(message.disabled);
    }
    if (message.collapsed !== false) {
      writer.uint32(64).bool(message.collapsed);
    }
    if (message.delayMs !== 0) {
      writer.uint32(72).int32(message.delayMs);
    }
    if (message.stepId !== "") {
      writer.uint32(82).string(message.stepId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionStep {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionStep();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stepRunnerKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = ActionStep_InputParamsEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.inputParams[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = ActionStep_OutputParamsEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.outputParams[entry3.key] = entry3.value;
          }
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.ifSteps.push(ActionStep.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.elseSteps.push(ActionStep.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.note = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.disabled = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.collapsed = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.delayMs = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.stepId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionStep {
    return {
      stepRunnerKey: isSet(object.stepRunnerKey) ? globalThis.String(object.stepRunnerKey) : "",
      inputParams: isObject(object.inputParams)
        ? Object.entries(object.inputParams).reduce<{ [key: string]: ActionStepParam }>((acc, [key, value]) => {
          acc[key] = ActionStepParam.fromJSON(value);
          return acc;
        }, {})
        : {},
      outputParams: isObject(object.outputParams)
        ? Object.entries(object.outputParams).reduce<{ [key: string]: string }>((acc, [key, value]) => {
          acc[key] = String(value);
          return acc;
        }, {})
        : {},
      ifSteps: globalThis.Array.isArray(object?.ifSteps) ? object.ifSteps.map((e: any) => ActionStep.fromJSON(e)) : [],
      elseSteps: globalThis.Array.isArray(object?.elseSteps)
        ? object.elseSteps.map((e: any) => ActionStep.fromJSON(e))
        : [],
      note: isSet(object.note) ? globalThis.String(object.note) : "",
      disabled: isSet(object.disabled) ? globalThis.Boolean(object.disabled) : false,
      collapsed: isSet(object.collapsed) ? globalThis.Boolean(object.collapsed) : false,
      delayMs: isSet(object.delayMs) ? globalThis.Number(object.delayMs) : 0,
      stepId: isSet(object.stepId) ? globalThis.String(object.stepId) : "",
    };
  },

  toJSON(message: ActionStep): unknown {
    const obj: any = {};
    if (message.stepRunnerKey !== "") {
      obj.stepRunnerKey = message.stepRunnerKey;
    }
    if (message.inputParams) {
      const entries = Object.entries(message.inputParams);
      if (entries.length > 0) {
        obj.inputParams = {};
        entries.forEach(([k, v]) => {
          obj.inputParams[k] = ActionStepParam.toJSON(v);
        });
      }
    }
    if (message.outputParams) {
      const entries = Object.entries(message.outputParams);
      if (entries.length > 0) {
        obj.outputParams = {};
        entries.forEach(([k, v]) => {
          obj.outputParams[k] = v;
        });
      }
    }
    if (message.ifSteps?.length) {
      obj.ifSteps = message.ifSteps.map((e) => ActionStep.toJSON(e));
    }
    if (message.elseSteps?.length) {
      obj.elseSteps = message.elseSteps.map((e) => ActionStep.toJSON(e));
    }
    if (message.note !== "") {
      obj.note = message.note;
    }
    if (message.disabled !== false) {
      obj.disabled = message.disabled;
    }
    if (message.collapsed !== false) {
      obj.collapsed = message.collapsed;
    }
    if (message.delayMs !== 0) {
      obj.delayMs = Math.round(message.delayMs);
    }
    if (message.stepId !== "") {
      obj.stepId = message.stepId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionStep>, I>>(base?: I): ActionStep {
    return ActionStep.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionStep>, I>>(object: I): ActionStep {
    const message = createBaseActionStep();
    message.stepRunnerKey = object.stepRunnerKey ?? "";
    message.inputParams = Object.entries(object.inputParams ?? {}).reduce<{ [key: string]: ActionStepParam }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = ActionStepParam.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.outputParams = Object.entries(object.outputParams ?? {}).reduce<{ [key: string]: string }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    message.ifSteps = object.ifSteps?.map((e) => ActionStep.fromPartial(e)) || [];
    message.elseSteps = object.elseSteps?.map((e) => ActionStep.fromPartial(e)) || [];
    message.note = object.note ?? "";
    message.disabled = object.disabled ?? false;
    message.collapsed = object.collapsed ?? false;
    message.delayMs = object.delayMs ?? 0;
    message.stepId = object.stepId ?? "";
    return message;
  },
};

function createBaseActionStep_InputParamsEntry(): ActionStep_InputParamsEntry {
  return { key: "", value: undefined };
}

export const ActionStep_InputParamsEntry: MessageFns<ActionStep_InputParamsEntry> = {
  encode(message: ActionStep_InputParamsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      ActionStepParam.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionStep_InputParamsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionStep_InputParamsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = ActionStepParam.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionStep_InputParamsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? ActionStepParam.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: ActionStep_InputParamsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = ActionStepParam.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionStep_InputParamsEntry>, I>>(base?: I): ActionStep_InputParamsEntry {
    return ActionStep_InputParamsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionStep_InputParamsEntry>, I>>(object: I): ActionStep_InputParamsEntry {
    const message = createBaseActionStep_InputParamsEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? ActionStepParam.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseActionStep_OutputParamsEntry(): ActionStep_OutputParamsEntry {
  return { key: "", value: "" };
}

export const ActionStep_OutputParamsEntry: MessageFns<ActionStep_OutputParamsEntry> = {
  encode(message: ActionStep_OutputParamsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionStep_OutputParamsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionStep_OutputParamsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionStep_OutputParamsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: ActionStep_OutputParamsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionStep_OutputParamsEntry>, I>>(base?: I): ActionStep_OutputParamsEntry {
    return ActionStep_OutputParamsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionStep_OutputParamsEntry>, I>>(object: I): ActionStep_OutputParamsEntry {
    const message = createBaseActionStep_OutputParamsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseActionSubProgram(): ActionSubProgram {
  return {
    id: "",
    name: "",
    description: "",
    icon: "",
    kind: 0,
    stepCount: 0,
    variableCount: 0,
    variables: [],
    steps: [],
    subPrograms: [],
  };
}

export const ActionSubProgram: MessageFns<ActionSubProgram> = {
  encode(message: ActionSubProgram, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.icon !== "") {
      writer.uint32(34).string(message.icon);
    }
    if (message.kind !== 0) {
      writer.uint32(40).int32(message.kind);
    }
    if (message.stepCount !== 0) {
      writer.uint32(48).int32(message.stepCount);
    }
    if (message.variableCount !== 0) {
      writer.uint32(56).int32(message.variableCount);
    }
    for (const v of message.variables) {
      ActionVariable.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.steps) {
      ActionStep.encode(v!, writer.uint32(74).fork()).join();
    }
    for (const v of message.subPrograms) {
      ActionSubProgram.encode(v!, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionSubProgram {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionSubProgram();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.kind = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.stepCount = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.variableCount = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.variables.push(ActionVariable.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.steps.push(ActionStep.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.subPrograms.push(ActionSubProgram.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionSubProgram {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
      kind: isSet(object.kind) ? globalThis.Number(object.kind) : 0,
      stepCount: isSet(object.stepCount) ? globalThis.Number(object.stepCount) : 0,
      variableCount: isSet(object.variableCount) ? globalThis.Number(object.variableCount) : 0,
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => ActionVariable.fromJSON(e))
        : [],
      steps: globalThis.Array.isArray(object?.steps) ? object.steps.map((e: any) => ActionStep.fromJSON(e)) : [],
      subPrograms: globalThis.Array.isArray(object?.subPrograms)
        ? object.subPrograms.map((e: any) => ActionSubProgram.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ActionSubProgram): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    if (message.kind !== 0) {
      obj.kind = Math.round(message.kind);
    }
    if (message.stepCount !== 0) {
      obj.stepCount = Math.round(message.stepCount);
    }
    if (message.variableCount !== 0) {
      obj.variableCount = Math.round(message.variableCount);
    }
    if (message.variables?.length) {
      obj.variables = message.variables.map((e) => ActionVariable.toJSON(e));
    }
    if (message.steps?.length) {
      obj.steps = message.steps.map((e) => ActionStep.toJSON(e));
    }
    if (message.subPrograms?.length) {
      obj.subPrograms = message.subPrograms.map((e) => ActionSubProgram.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionSubProgram>, I>>(base?: I): ActionSubProgram {
    return ActionSubProgram.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionSubProgram>, I>>(object: I): ActionSubProgram {
    const message = createBaseActionSubProgram();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.icon = object.icon ?? "";
    message.kind = object.kind ?? 0;
    message.stepCount = object.stepCount ?? 0;
    message.variableCount = object.variableCount ?? 0;
    message.variables = object.variables?.map((e) => ActionVariable.fromPartial(e)) || [];
    message.steps = object.steps?.map((e) => ActionStep.fromPartial(e)) || [];
    message.subPrograms = object.subPrograms?.map((e) => ActionSubProgram.fromPartial(e)) || [];
    return message;
  },
};

function createBaseValidationIssue(): ValidationIssue {
  return { code: "", message: "", targetPath: "", severity: "" };
}

export const ValidationIssue: MessageFns<ValidationIssue> = {
  encode(message: ValidationIssue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    if (message.targetPath !== "") {
      writer.uint32(26).string(message.targetPath);
    }
    if (message.severity !== "") {
      writer.uint32(34).string(message.severity);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ValidationIssue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseValidationIssue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.targetPath = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.severity = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ValidationIssue {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      targetPath: isSet(object.targetPath) ? globalThis.String(object.targetPath) : "",
      severity: isSet(object.severity) ? globalThis.String(object.severity) : "",
    };
  },

  toJSON(message: ValidationIssue): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.targetPath !== "") {
      obj.targetPath = message.targetPath;
    }
    if (message.severity !== "") {
      obj.severity = message.severity;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ValidationIssue>, I>>(base?: I): ValidationIssue {
    return ValidationIssue.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ValidationIssue>, I>>(object: I): ValidationIssue {
    const message = createBaseValidationIssue();
    message.code = object.code ?? "";
    message.message = object.message ?? "";
    message.targetPath = object.targetPath ?? "";
    message.severity = object.severity ?? "";
    return message;
  },
};

function createBaseCommandDiffSummary(): CommandDiffSummary {
  return { title: "", changedPaths: [] };
}

export const CommandDiffSummary: MessageFns<CommandDiffSummary> = {
  encode(message: CommandDiffSummary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    for (const v of message.changedPaths) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommandDiffSummary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommandDiffSummary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.changedPaths.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommandDiffSummary {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      changedPaths: globalThis.Array.isArray(object?.changedPaths)
        ? object.changedPaths.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: CommandDiffSummary): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.changedPaths?.length) {
      obj.changedPaths = message.changedPaths;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommandDiffSummary>, I>>(base?: I): CommandDiffSummary {
    return CommandDiffSummary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommandDiffSummary>, I>>(object: I): CommandDiffSummary {
    const message = createBaseCommandDiffSummary();
    message.title = object.title ?? "";
    message.changedPaths = object.changedPaths?.map((e) => e) || [];
    return message;
  },
};

function createBaseRequestContext(): RequestContext {
  return { operatorId: "", traceId: "" };
}

export const RequestContext: MessageFns<RequestContext> = {
  encode(message: RequestContext, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.operatorId !== "") {
      writer.uint32(10).string(message.operatorId);
    }
    if (message.traceId !== "") {
      writer.uint32(18).string(message.traceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestContext {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestContext();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.operatorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.traceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestContext {
    return {
      operatorId: isSet(object.operatorId) ? globalThis.String(object.operatorId) : "",
      traceId: isSet(object.traceId) ? globalThis.String(object.traceId) : "",
    };
  },

  toJSON(message: RequestContext): unknown {
    const obj: any = {};
    if (message.operatorId !== "") {
      obj.operatorId = message.operatorId;
    }
    if (message.traceId !== "") {
      obj.traceId = message.traceId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestContext>, I>>(base?: I): RequestContext {
    return RequestContext.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestContext>, I>>(object: I): RequestContext {
    const message = createBaseRequestContext();
    message.operatorId = object.operatorId ?? "";
    message.traceId = object.traceId ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
