// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v3.19.1
// source: global_subprogram_io.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ActionVariable } from "./common";

export interface GetGlobalSubProgramIoRequest {
  /** Stable id from UI (%%guid token, XSubProgramData.Id, ActionSubProgram.id). */
  subProgramId: string;
  /**
   * Optional: current sys:subprogram step JSON (web ActionStep / camelCase) so the host can
   * merge binding state into binding_hints for the popup.
   */
  callerStepJson?: string | undefined;
}

/** Per-variable binding snapshot from caller_step_json input_params (var:* keys). */
export interface SubProgramIoBindingHint {
  /** Matches ActionVariable.key — expected key on the calling step param map. */
  variableKey: string;
  isBound: boolean;
  /** Raw bound expression/literal from step JSON when is_bound. */
  boundValue: string;
}

export interface GetGlobalSubProgramIoResponse {
  found: boolean;
  subProgramId: string;
  displayName: string;
  description: string;
  icon: string;
  /** Same numeric meaning as ActionSubProgram.kind (0 unspecified, 1 internal, 2 global link, …). */
  kind: number;
  /** Variables with is_input == true, in host-defined stable order (e.g. definition order). */
  inputs: ActionVariable[];
  /** Variables with is_output == true. */
  outputs: ActionVariable[];
  /** Populated when caller_step_json was set; one row per input variable key when useful. */
  bindingHints: SubProgramIoBindingHint[];
  /** Human-readable reason when found == false (unknown id, host not in Quicker, etc.). */
  resolveStatusMessage: string;
}

function createBaseGetGlobalSubProgramIoRequest(): GetGlobalSubProgramIoRequest {
  return { subProgramId: "", callerStepJson: undefined };
}

export const GetGlobalSubProgramIoRequest: MessageFns<GetGlobalSubProgramIoRequest> = {
  encode(message: GetGlobalSubProgramIoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subProgramId !== "") {
      writer.uint32(10).string(message.subProgramId);
    }
    if (message.callerStepJson !== undefined) {
      writer.uint32(18).string(message.callerStepJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGlobalSubProgramIoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGlobalSubProgramIoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subProgramId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.callerStepJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGlobalSubProgramIoRequest {
    return {
      subProgramId: isSet(object.subProgramId) ? globalThis.String(object.subProgramId) : "",
      callerStepJson: isSet(object.callerStepJson) ? globalThis.String(object.callerStepJson) : undefined,
    };
  },

  toJSON(message: GetGlobalSubProgramIoRequest): unknown {
    const obj: any = {};
    if (message.subProgramId !== "") {
      obj.subProgramId = message.subProgramId;
    }
    if (message.callerStepJson !== undefined) {
      obj.callerStepJson = message.callerStepJson;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGlobalSubProgramIoRequest>, I>>(base?: I): GetGlobalSubProgramIoRequest {
    return GetGlobalSubProgramIoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGlobalSubProgramIoRequest>, I>>(object: I): GetGlobalSubProgramIoRequest {
    const message = createBaseGetGlobalSubProgramIoRequest();
    message.subProgramId = object.subProgramId ?? "";
    message.callerStepJson = object.callerStepJson ?? undefined;
    return message;
  },
};

function createBaseSubProgramIoBindingHint(): SubProgramIoBindingHint {
  return { variableKey: "", isBound: false, boundValue: "" };
}

export const SubProgramIoBindingHint: MessageFns<SubProgramIoBindingHint> = {
  encode(message: SubProgramIoBindingHint, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.variableKey !== "") {
      writer.uint32(10).string(message.variableKey);
    }
    if (message.isBound !== false) {
      writer.uint32(16).bool(message.isBound);
    }
    if (message.boundValue !== "") {
      writer.uint32(26).string(message.boundValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubProgramIoBindingHint {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubProgramIoBindingHint();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.variableKey = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isBound = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.boundValue = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubProgramIoBindingHint {
    return {
      variableKey: isSet(object.variableKey) ? globalThis.String(object.variableKey) : "",
      isBound: isSet(object.isBound) ? globalThis.Boolean(object.isBound) : false,
      boundValue: isSet(object.boundValue) ? globalThis.String(object.boundValue) : "",
    };
  },

  toJSON(message: SubProgramIoBindingHint): unknown {
    const obj: any = {};
    if (message.variableKey !== "") {
      obj.variableKey = message.variableKey;
    }
    if (message.isBound !== false) {
      obj.isBound = message.isBound;
    }
    if (message.boundValue !== "") {
      obj.boundValue = message.boundValue;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubProgramIoBindingHint>, I>>(base?: I): SubProgramIoBindingHint {
    return SubProgramIoBindingHint.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubProgramIoBindingHint>, I>>(object: I): SubProgramIoBindingHint {
    const message = createBaseSubProgramIoBindingHint();
    message.variableKey = object.variableKey ?? "";
    message.isBound = object.isBound ?? false;
    message.boundValue = object.boundValue ?? "";
    return message;
  },
};

function createBaseGetGlobalSubProgramIoResponse(): GetGlobalSubProgramIoResponse {
  return {
    found: false,
    subProgramId: "",
    displayName: "",
    description: "",
    icon: "",
    kind: 0,
    inputs: [],
    outputs: [],
    bindingHints: [],
    resolveStatusMessage: "",
  };
}

export const GetGlobalSubProgramIoResponse: MessageFns<GetGlobalSubProgramIoResponse> = {
  encode(message: GetGlobalSubProgramIoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.found !== false) {
      writer.uint32(8).bool(message.found);
    }
    if (message.subProgramId !== "") {
      writer.uint32(18).string(message.subProgramId);
    }
    if (message.displayName !== "") {
      writer.uint32(26).string(message.displayName);
    }
    if (message.description !== "") {
      writer.uint32(34).string(message.description);
    }
    if (message.icon !== "") {
      writer.uint32(42).string(message.icon);
    }
    if (message.kind !== 0) {
      writer.uint32(48).int32(message.kind);
    }
    for (const v of message.inputs) {
      ActionVariable.encode(v!, writer.uint32(58).fork()).join();
    }
    for (const v of message.outputs) {
      ActionVariable.encode(v!, writer.uint32(66).fork()).join();
    }
    for (const v of message.bindingHints) {
      SubProgramIoBindingHint.encode(v!, writer.uint32(74).fork()).join();
    }
    if (message.resolveStatusMessage !== "") {
      writer.uint32(82).string(message.resolveStatusMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetGlobalSubProgramIoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetGlobalSubProgramIoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.found = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.subProgramId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.displayName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.kind = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.inputs.push(ActionVariable.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.outputs.push(ActionVariable.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.bindingHints.push(SubProgramIoBindingHint.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.resolveStatusMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetGlobalSubProgramIoResponse {
    return {
      found: isSet(object.found) ? globalThis.Boolean(object.found) : false,
      subProgramId: isSet(object.subProgramId) ? globalThis.String(object.subProgramId) : "",
      displayName: isSet(object.displayName) ? globalThis.String(object.displayName) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
      kind: isSet(object.kind) ? globalThis.Number(object.kind) : 0,
      inputs: globalThis.Array.isArray(object?.inputs) ? object.inputs.map((e: any) => ActionVariable.fromJSON(e)) : [],
      outputs: globalThis.Array.isArray(object?.outputs)
        ? object.outputs.map((e: any) => ActionVariable.fromJSON(e))
        : [],
      bindingHints: globalThis.Array.isArray(object?.bindingHints)
        ? object.bindingHints.map((e: any) => SubProgramIoBindingHint.fromJSON(e))
        : [],
      resolveStatusMessage: isSet(object.resolveStatusMessage) ? globalThis.String(object.resolveStatusMessage) : "",
    };
  },

  toJSON(message: GetGlobalSubProgramIoResponse): unknown {
    const obj: any = {};
    if (message.found !== false) {
      obj.found = message.found;
    }
    if (message.subProgramId !== "") {
      obj.subProgramId = message.subProgramId;
    }
    if (message.displayName !== "") {
      obj.displayName = message.displayName;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    if (message.kind !== 0) {
      obj.kind = Math.round(message.kind);
    }
    if (message.inputs?.length) {
      obj.inputs = message.inputs.map((e) => ActionVariable.toJSON(e));
    }
    if (message.outputs?.length) {
      obj.outputs = message.outputs.map((e) => ActionVariable.toJSON(e));
    }
    if (message.bindingHints?.length) {
      obj.bindingHints = message.bindingHints.map((e) => SubProgramIoBindingHint.toJSON(e));
    }
    if (message.resolveStatusMessage !== "") {
      obj.resolveStatusMessage = message.resolveStatusMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetGlobalSubProgramIoResponse>, I>>(base?: I): GetGlobalSubProgramIoResponse {
    return GetGlobalSubProgramIoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetGlobalSubProgramIoResponse>, I>>(
    object: I,
  ): GetGlobalSubProgramIoResponse {
    const message = createBaseGetGlobalSubProgramIoResponse();
    message.found = object.found ?? false;
    message.subProgramId = object.subProgramId ?? "";
    message.displayName = object.displayName ?? "";
    message.description = object.description ?? "";
    message.icon = object.icon ?? "";
    message.kind = object.kind ?? 0;
    message.inputs = object.inputs?.map((e) => ActionVariable.fromPartial(e)) || [];
    message.outputs = object.outputs?.map((e) => ActionVariable.fromPartial(e)) || [];
    message.bindingHints = object.bindingHints?.map((e) => SubProgramIoBindingHint.fromPartial(e)) || [];
    message.resolveStatusMessage = object.resolveStatusMessage ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
