// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v3.19.1
// source: shared_subprogram.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ActionSubProgram } from "./common";

/** One row from Quicker share-library search (Web network sub program sidebar). */
export interface SharedSubProgramListItem {
  id: string;
  title: string;
  description: string;
  icon: string;
  tags: string;
  note: string;
  revision: number;
  lastUpdateTimeUtc: string;
  useCount: number;
  createTimeUtc: string;
  userNickName: string;
  userSerial: number;
  voteCount: number;
  isPublic: boolean;
}

export interface QuerySharedSubProgramsRequest {
  keyword: string;
}

export interface QuerySharedSubProgramsResponse {
  ok: boolean;
  message: string;
  items: SharedSubProgramListItem[];
}

export interface GetSharedSubProgramRequest {
  /** Network identifier @@guid@revision@title (preferred) or bare guid. */
  identifier: string;
}

export interface GetSharedSubProgramResponse {
  found: boolean;
  resolveStatusMessage: string;
  program?: ActionSubProgram | undefined;
}

export interface GetSharedSubProgramIoRequest {
  /** Same as GetSharedSubProgramRequest.identifier. */
  identifier: string;
  callerStepJson?: string | undefined;
}

function createBaseSharedSubProgramListItem(): SharedSubProgramListItem {
  return {
    id: "",
    title: "",
    description: "",
    icon: "",
    tags: "",
    note: "",
    revision: 0,
    lastUpdateTimeUtc: "",
    useCount: 0,
    createTimeUtc: "",
    userNickName: "",
    userSerial: 0,
    voteCount: 0,
    isPublic: false,
  };
}

export const SharedSubProgramListItem: MessageFns<SharedSubProgramListItem> = {
  encode(message: SharedSubProgramListItem, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.icon !== "") {
      writer.uint32(34).string(message.icon);
    }
    if (message.tags !== "") {
      writer.uint32(42).string(message.tags);
    }
    if (message.note !== "") {
      writer.uint32(50).string(message.note);
    }
    if (message.revision !== 0) {
      writer.uint32(56).int32(message.revision);
    }
    if (message.lastUpdateTimeUtc !== "") {
      writer.uint32(66).string(message.lastUpdateTimeUtc);
    }
    if (message.useCount !== 0) {
      writer.uint32(72).int32(message.useCount);
    }
    if (message.createTimeUtc !== "") {
      writer.uint32(82).string(message.createTimeUtc);
    }
    if (message.userNickName !== "") {
      writer.uint32(90).string(message.userNickName);
    }
    if (message.userSerial !== 0) {
      writer.uint32(96).int32(message.userSerial);
    }
    if (message.voteCount !== 0) {
      writer.uint32(104).int32(message.voteCount);
    }
    if (message.isPublic !== false) {
      writer.uint32(112).bool(message.isPublic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SharedSubProgramListItem {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSharedSubProgramListItem();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tags = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.note = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.revision = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.lastUpdateTimeUtc = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.useCount = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.createTimeUtc = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.userNickName = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.userSerial = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.voteCount = reader.int32();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.isPublic = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SharedSubProgramListItem {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      icon: isSet(object.icon) ? globalThis.String(object.icon) : "",
      tags: isSet(object.tags) ? globalThis.String(object.tags) : "",
      note: isSet(object.note) ? globalThis.String(object.note) : "",
      revision: isSet(object.revision) ? globalThis.Number(object.revision) : 0,
      lastUpdateTimeUtc: isSet(object.lastUpdateTimeUtc) ? globalThis.String(object.lastUpdateTimeUtc) : "",
      useCount: isSet(object.useCount) ? globalThis.Number(object.useCount) : 0,
      createTimeUtc: isSet(object.createTimeUtc) ? globalThis.String(object.createTimeUtc) : "",
      userNickName: isSet(object.userNickName) ? globalThis.String(object.userNickName) : "",
      userSerial: isSet(object.userSerial) ? globalThis.Number(object.userSerial) : 0,
      voteCount: isSet(object.voteCount) ? globalThis.Number(object.voteCount) : 0,
      isPublic: isSet(object.isPublic) ? globalThis.Boolean(object.isPublic) : false,
    };
  },

  toJSON(message: SharedSubProgramListItem): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.icon !== "") {
      obj.icon = message.icon;
    }
    if (message.tags !== "") {
      obj.tags = message.tags;
    }
    if (message.note !== "") {
      obj.note = message.note;
    }
    if (message.revision !== 0) {
      obj.revision = Math.round(message.revision);
    }
    if (message.lastUpdateTimeUtc !== "") {
      obj.lastUpdateTimeUtc = message.lastUpdateTimeUtc;
    }
    if (message.useCount !== 0) {
      obj.useCount = Math.round(message.useCount);
    }
    if (message.createTimeUtc !== "") {
      obj.createTimeUtc = message.createTimeUtc;
    }
    if (message.userNickName !== "") {
      obj.userNickName = message.userNickName;
    }
    if (message.userSerial !== 0) {
      obj.userSerial = Math.round(message.userSerial);
    }
    if (message.voteCount !== 0) {
      obj.voteCount = Math.round(message.voteCount);
    }
    if (message.isPublic !== false) {
      obj.isPublic = message.isPublic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SharedSubProgramListItem>, I>>(base?: I): SharedSubProgramListItem {
    return SharedSubProgramListItem.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SharedSubProgramListItem>, I>>(object: I): SharedSubProgramListItem {
    const message = createBaseSharedSubProgramListItem();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.icon = object.icon ?? "";
    message.tags = object.tags ?? "";
    message.note = object.note ?? "";
    message.revision = object.revision ?? 0;
    message.lastUpdateTimeUtc = object.lastUpdateTimeUtc ?? "";
    message.useCount = object.useCount ?? 0;
    message.createTimeUtc = object.createTimeUtc ?? "";
    message.userNickName = object.userNickName ?? "";
    message.userSerial = object.userSerial ?? 0;
    message.voteCount = object.voteCount ?? 0;
    message.isPublic = object.isPublic ?? false;
    return message;
  },
};

function createBaseQuerySharedSubProgramsRequest(): QuerySharedSubProgramsRequest {
  return { keyword: "" };
}

export const QuerySharedSubProgramsRequest: MessageFns<QuerySharedSubProgramsRequest> = {
  encode(message: QuerySharedSubProgramsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.keyword !== "") {
      writer.uint32(10).string(message.keyword);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySharedSubProgramsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuerySharedSubProgramsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.keyword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuerySharedSubProgramsRequest {
    return { keyword: isSet(object.keyword) ? globalThis.String(object.keyword) : "" };
  },

  toJSON(message: QuerySharedSubProgramsRequest): unknown {
    const obj: any = {};
    if (message.keyword !== "") {
      obj.keyword = message.keyword;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuerySharedSubProgramsRequest>, I>>(base?: I): QuerySharedSubProgramsRequest {
    return QuerySharedSubProgramsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuerySharedSubProgramsRequest>, I>>(
    object: I,
  ): QuerySharedSubProgramsRequest {
    const message = createBaseQuerySharedSubProgramsRequest();
    message.keyword = object.keyword ?? "";
    return message;
  },
};

function createBaseQuerySharedSubProgramsResponse(): QuerySharedSubProgramsResponse {
  return { ok: false, message: "", items: [] };
}

export const QuerySharedSubProgramsResponse: MessageFns<QuerySharedSubProgramsResponse> = {
  encode(message: QuerySharedSubProgramsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ok !== false) {
      writer.uint32(8).bool(message.ok);
    }
    if (message.message !== "") {
      writer.uint32(18).string(message.message);
    }
    for (const v of message.items) {
      SharedSubProgramListItem.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): QuerySharedSubProgramsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseQuerySharedSubProgramsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.message = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.items.push(SharedSubProgramListItem.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): QuerySharedSubProgramsResponse {
    return {
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      message: isSet(object.message) ? globalThis.String(object.message) : "",
      items: globalThis.Array.isArray(object?.items)
        ? object.items.map((e: any) => SharedSubProgramListItem.fromJSON(e))
        : [],
    };
  },

  toJSON(message: QuerySharedSubProgramsResponse): unknown {
    const obj: any = {};
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    if (message.items?.length) {
      obj.items = message.items.map((e) => SharedSubProgramListItem.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<QuerySharedSubProgramsResponse>, I>>(base?: I): QuerySharedSubProgramsResponse {
    return QuerySharedSubProgramsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<QuerySharedSubProgramsResponse>, I>>(
    object: I,
  ): QuerySharedSubProgramsResponse {
    const message = createBaseQuerySharedSubProgramsResponse();
    message.ok = object.ok ?? false;
    message.message = object.message ?? "";
    message.items = object.items?.map((e) => SharedSubProgramListItem.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetSharedSubProgramRequest(): GetSharedSubProgramRequest {
  return { identifier: "" };
}

export const GetSharedSubProgramRequest: MessageFns<GetSharedSubProgramRequest> = {
  encode(message: GetSharedSubProgramRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identifier !== "") {
      writer.uint32(10).string(message.identifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSharedSubProgramRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSharedSubProgramRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSharedSubProgramRequest {
    return { identifier: isSet(object.identifier) ? globalThis.String(object.identifier) : "" };
  },

  toJSON(message: GetSharedSubProgramRequest): unknown {
    const obj: any = {};
    if (message.identifier !== "") {
      obj.identifier = message.identifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSharedSubProgramRequest>, I>>(base?: I): GetSharedSubProgramRequest {
    return GetSharedSubProgramRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSharedSubProgramRequest>, I>>(object: I): GetSharedSubProgramRequest {
    const message = createBaseGetSharedSubProgramRequest();
    message.identifier = object.identifier ?? "";
    return message;
  },
};

function createBaseGetSharedSubProgramResponse(): GetSharedSubProgramResponse {
  return { found: false, resolveStatusMessage: "", program: undefined };
}

export const GetSharedSubProgramResponse: MessageFns<GetSharedSubProgramResponse> = {
  encode(message: GetSharedSubProgramResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.found !== false) {
      writer.uint32(8).bool(message.found);
    }
    if (message.resolveStatusMessage !== "") {
      writer.uint32(18).string(message.resolveStatusMessage);
    }
    if (message.program !== undefined) {
      ActionSubProgram.encode(message.program, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSharedSubProgramResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSharedSubProgramResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.found = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resolveStatusMessage = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.program = ActionSubProgram.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSharedSubProgramResponse {
    return {
      found: isSet(object.found) ? globalThis.Boolean(object.found) : false,
      resolveStatusMessage: isSet(object.resolveStatusMessage) ? globalThis.String(object.resolveStatusMessage) : "",
      program: isSet(object.program) ? ActionSubProgram.fromJSON(object.program) : undefined,
    };
  },

  toJSON(message: GetSharedSubProgramResponse): unknown {
    const obj: any = {};
    if (message.found !== false) {
      obj.found = message.found;
    }
    if (message.resolveStatusMessage !== "") {
      obj.resolveStatusMessage = message.resolveStatusMessage;
    }
    if (message.program !== undefined) {
      obj.program = ActionSubProgram.toJSON(message.program);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSharedSubProgramResponse>, I>>(base?: I): GetSharedSubProgramResponse {
    return GetSharedSubProgramResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSharedSubProgramResponse>, I>>(object: I): GetSharedSubProgramResponse {
    const message = createBaseGetSharedSubProgramResponse();
    message.found = object.found ?? false;
    message.resolveStatusMessage = object.resolveStatusMessage ?? "";
    message.program = (object.program !== undefined && object.program !== null)
      ? ActionSubProgram.fromPartial(object.program)
      : undefined;
    return message;
  },
};

function createBaseGetSharedSubProgramIoRequest(): GetSharedSubProgramIoRequest {
  return { identifier: "", callerStepJson: undefined };
}

export const GetSharedSubProgramIoRequest: MessageFns<GetSharedSubProgramIoRequest> = {
  encode(message: GetSharedSubProgramIoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.identifier !== "") {
      writer.uint32(10).string(message.identifier);
    }
    if (message.callerStepJson !== undefined) {
      writer.uint32(18).string(message.callerStepJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetSharedSubProgramIoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSharedSubProgramIoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.identifier = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.callerStepJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetSharedSubProgramIoRequest {
    return {
      identifier: isSet(object.identifier) ? globalThis.String(object.identifier) : "",
      callerStepJson: isSet(object.callerStepJson) ? globalThis.String(object.callerStepJson) : undefined,
    };
  },

  toJSON(message: GetSharedSubProgramIoRequest): unknown {
    const obj: any = {};
    if (message.identifier !== "") {
      obj.identifier = message.identifier;
    }
    if (message.callerStepJson !== undefined) {
      obj.callerStepJson = message.callerStepJson;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSharedSubProgramIoRequest>, I>>(base?: I): GetSharedSubProgramIoRequest {
    return GetSharedSubProgramIoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSharedSubProgramIoRequest>, I>>(object: I): GetSharedSubProgramIoRequest {
    const message = createBaseGetSharedSubProgramIoRequest();
    message.identifier = object.identifier ?? "";
    message.callerStepJson = object.callerStepJson ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
